### ISSUE TITLE
Our Team Widget Improvements

### ISSUE THREAD

**Issue by HardeepAsrani** [Codeinwp/zerif-lite#102]
Links that are on 'our member' Even at 'Our focus', it'd be good to have option to make it open in new window.

But on our Our Member section IS the must! And even better if we can add website link to our member picture.

@ineagu

**Comment by oobbles** [comment]
I agree! I'd love for all the links in the Team Members area to open in a new window.

**Comment by ineagu** [comment]
@rodica-andronache whatis the status here ? I think we have target-blank right ?

**Comment by rodica-andronache** [comment]
@ineagu here you only mean the social icons, to have an option to open in a new tab? or also to add a option to add a link to the team member image ,and also an option for that link to open in a new window?

**Comment by ineagu** [comment]
for now probably just social icons to open in new window

On Tue, Sep 29, 2015 at 2:54 PM, Rodica-Elena Andronache <
notifications@github.com> wrote:

> @ineagu <https://github.com/ineagu> here you only mean the social icons,
> to have an option to open in a new tab? or also to add a option to add a
> link to the team member image ,and also an option for that link to open in
> a new window?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Codeinwp/zerif-lite/issues/102#issuecomment-144049771>
> .
>



-- 
Ionut Neagu
http://themeisle.com | http://codeinwp.com | http://ionutn.com
