### ISSUE TITLE
Unordered List issue

### ISSUE THREAD

**Issue by mileamadalin** [Codeinwp/zerif-lite#110]
Am primit acest mesaj pe forum: 

When I create an unordered list that follows a heading style, the first bullet does not appear.

If I add a blank line (standard paragraph style), the bullet shows up fine.

Unordered lists that follow a standard paragraph show up fine.

Un alt client confirma aceasta problema.

**Comment by HardeepAsrani** [comment]
@mileamadalin @ineagu @rodica-andronache 

This only appears when the lists are just below a heading tag, and only on web-kit browsers. The reasons being the float:left styling in the heading tags. :)
