### ISSUE TITLE
Issue with Firefox/Contact

### ISSUE THREAD

**Issue by HardeepAsrani** [Codeinwp/zerif-lite#117]
In Firefox, if we submit a reply in forums it reloads and shows the top of the page, instead of scrolling down to the contact section. @ineagu @rodica-andronache

**Comment by rodica-andronache** [comment]
In Contact-Form you try to save scroll postition on submit. It doesn't work for IE and Firefox on several Win7 and Win8 machines. Solution for me was: onSubmit="this.scrollPosition.value=(document.body.scrollTop || document.documentElement.scrollTop)"

**Comment by aurelijusrozenas** [comment]
@rodica-andronache your fix works for firefox. Why it is not commited yet?
It works when you successfully post form but if you get error, page will reload and will not scroll down. How to fix that?
