### ISSUE TITLE
Responsive issue

### ISSUE THREAD

**Issue by mileamadalin** [Codeinwp/zerif-lite#119]
@rodica-andronache @ineagu am primit acest mesaj de la client

"It looks great on a laptop and it looks fine on an ipad mini...but not on a
cell/mobile device

The logo is not centred properly and obscures the menu...and when you don't
select the menu the logo appears almost complety obscured...Not good."

este vorba despre logo-ul lui. Mai jos am atasat si doua poze sa vedeti despre ce este vorba. Au mai fost si alti clienti cu aceasta problema. 

In orice caz, momentan i-am recomandat sa micsoreze dimensiunea logo-ului, pentru a evita aceasta problema. Ma gandesc ca poate reusim sa facem ceva, ca pentru mobile version sa reusim cumva automat sa micsoram logo-ul (uniform) la dimensiunea necesara temei, ca sa evitam acest tip de probleme.

![1vandroid shot of ziingles com](https://cloud.githubusercontent.com/assets/6906834/7343529/9e157ff0-ecc2-11e4-8af3-571df05feec7.png)
![2v android shot of ziinglescom](https://cloud.githubusercontent.com/assets/6906834/7343530/9e15ab88-ecc2-11e4-85a8-2c5277ed3842.png)

**Comment by claudiuvertistudio** [comment]
@mileamadalin problema este rezolvata incepand cu versiunea 1.7.3 pentru lite si cu versiunea 1.6.7 pentru pro

**Comment by ineagu** [comment]
@mileamadalin inainte de a raporta orice issue, ar trebui sa te asiguri ca omul are ultima vers de tema/plugin . te poti uita cu view source in style.css

**Comment by mileamadalin** [comment]
@claudiuvertistudio clientul are ultima versiune  si problema nu este rezolvata.

**Comment by claudiuvertistudio** [comment]
@mileamadalin momentan nu s-a facut update, inca lucram pe development. Si nu e facut merge pe production

**Comment by rodica-andronache** [comment]
@claudiuvertistudio cred ca aici am incurcat cu pro. Nu cred ca ai rezolvat pe lite. Poti te rog, sa mai verifici?

**Comment by claudiuvertistudio** [comment]
@rodica-andronache am verificat si pe lite si este ok
