### ISSUE TITLE
Scrolling in Chrome is weird and inconsisten

### ISSUE THREAD

**Issue by mileamadalin** [Codeinwp/zerif-lite#120]
@rodica-andronache @claudiuvertistudio @ineagu avem o mica problema in Chrome cand se face scroll. Acesta problema o confirm si eu pentru ca am observat aceasi problema. 

"I grepped the Zerif Lite source for “scroll” and then “smoothscroll” and commented out the call to

wp_enqueue_script(‘zerif_smoothscroll’, get_template_directory_uri() . ‘/js/smoothscroll.js’, array(“jquery”), ‘20120206’, true);

in functions.php, and then all scrolling issues went away, at all magnifications I tested."

Aici a venit clientul cu o solutie care pentru el a functionat. Acum ramane sa o vedeti si voi si sa o aplicam daca este cea mai buna.

**Comment by segadora** [comment]
+1

**Comment by ineagu** [comment]
I agree that will be a good idea to give an option to users to remove this, also if existing users are not affected we can make this option default ( for the new users )
