### ISSUE TITLE
Change textboxes to multilined textboxes in customazation

### ISSUE THREAD

**Issue by HardeepAsrani** [Codeinwp/zerif-lite#143]
Source: ThemeIsle Forum

Not sure if this is the right place to submit this. I would be nice if you could make multilined text boxes on customization page for fields with bigger text sections. Really annoying to edit in them small textboxes.

Thanks,

@ineagu @rodica-andronache

**Comment by cristian-ungureanu** [comment]
@rodica-andronache , I've changed this for text in "about" section and for "ribbons". Let me know if there is another field that you want me to change. From what I've seen those were the only ones with posible bigger text section.
