### ISSUE TITLE
Font is not ready for other languages

### ISSUE THREAD

**Issue by aurelijusrozenas** [Codeinwp/zerif-lite#145]
In some headers Lithuanian letters are displayed in different font. Maybe import should reconfigured?

![zerif](https://cloud.githubusercontent.com/assets/3273544/7782696/5c6b10aa-012c-11e5-92d8-eb6be84543de.png)

**Comment by aurelijusrozenas** [comment]
Same in testimonials section.
![ekrano nuotrauka is 2015-05-23 11 19 19](https://cloud.githubusercontent.com/assets/3273544/7783098/a883a798-013d-11e5-85b9-1e084802c4f5.png)

**Comment by rodica-andronache** [comment]
@aurelijusrozenas sorry for the late answer :) 
Thank you for letting us know about this issue. I think we are going to add an option for the user, to be able to choose the desired font for the theme, and this should fix the issue.

**Comment by aurelijusrozenas** [comment]
While that true, it would be amazing if you included similar font or fix this if this is possible. Some themes offer to change fonts and even import them from google fonts, however it difficult to find font that is similar and it is not clear if new font will break style in some place.
