### ISSUE TITLE
about us alignment on mobile when two sections

### ISSUE THREAD

**Issue by rodica-andronache** [Codeinwp/zerif-lite#150]
---

While using 2 columns side by side on full width:
"Big Left Side Title" aligns right
## "Text" aligns left

---

While using 2 columns side by side reducing width step by step:
"Big Left Side Title" aligns right til a certain point where it centers shortly before the sections are arranged vertically (it should stay aligned right till the sections get aligned vertically)
## "Text" aligns left

---

While using 2 columns and width reduced to arrange them vertically:
"Big Left Side Title" aligns centered
## "Text" aligns left (Shouldn't it be centered?)

Checked briefly on section 3 and it aligns left all time... Shouldn't in align centered when the sections scale vertically?

**Comment by claudiuvertistudio** [comment]
@ineagu aici fac ceva? sau las asa cume e acum tema?

**Comment by ineagu** [comment]
la ce se refera mai exact ?

**Comment by claudiuvertistudio** [comment]
@ineagu sa centrez textul la sectiunea de about ca aici
https://drive.google.com/a/vertistudio.com/file/d/0B-5bubkEZeL-dmFaVi0zNFROTGs/edit?usp=drivesdk

**Comment by ineagu** [comment]
daca nu au zis prea multi putem lasa asa, lumea a folosit poate sectiunea aia in diverse feluri si sa nu crape
