### ISSUE TITLE
Scrolling issue

### ISSUE THREAD

**Issue by mileamadalin** [Codeinwp/zerif-lite#167]
@rodica-andronache cand intru pentru prima oara pe pagina si vreau sa fac scroll sa vad urmatoarele sectiuni, trebuie sa invart rotita de 3-4 ori ca sa porneasca. Aceasta problema apare de cate ori vreau sa fac scroll in jos din sectiunea big title.

Mentionez ca asta mi se intampla doar pe Chrome (mac)

**Comment by claudiuvertistudio** [comment]
Este din cauza pluginului smoothscroll.min.js. nu am ce sa-i fac
