### ISSUE TITLE
Replace require and include with load_template

### ISSUE THREAD

**Issue by rodica-andronache** [Codeinwp/zerif-lite#181]
to allow child themes to override templates
http://themeisle.com/forums/topic/change-file-included-with-require/

**Comment by tkes** [comment]
Would suggest to use [get_template_part()](https://codex.wordpress.org/Function_Reference/get_template_part) which is the official way to provide child theme override possibilites, see also [example fix here](https://wordpress.org/support/topic/child-theme-fix-use-get_template_part-instead-include-get_template_directory?replies=3).

**Comment by rodica-andronache** [comment]
@tkes thank you! That's what we are going to do in the next update.
