### ISSUE TITLE
upgrade to pro links to open a popup

### ISSUE THREAD

**Issue by ineagu** [Codeinwp/zerif-lite#185]
@rodica-andronache ca sa putem arata mai bine oamenilor ce avem in versiunea pro, ma gandeam ca atunci cand lumea da click pe upgrade to pro din customizer, sa ii deschida un popup, cu un mic slider cu diverse chestii pe care le poate face in PRO ( ca aici : https://www.evernote.com/l/AY-nrTHHe5JEYbdr03n5TyguExGCFhHFhPE )

**Comment by rodica-andronache** [comment]
@ineagu ne-ar permite asta acum pe wp.org?

**Comment by ineagu** [comment]
nu prea, pt ca teoretic avem about zerif lite unde putem sa facem asta

On Thu, Apr 7, 2016 at 11:44 AM, Rodica-Elena Andronache <
notifications@github.com> wrote:

> @ineagu <https://github.com/ineagu> ne-ar permite asta acum pe wp.org?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/Codeinwp/zerif-lite/issues/185#issuecomment-206762385>
>



-- 
Ionut Neagu
http://themeisle.com | http://codeinwp.com | http://ionutn.com
