### ISSUE TITLE
show the team widget area in the team setting section

### ISSUE THREAD

**Issue by ineagu** [Codeinwp/zerif-lite#186]
@rodica-andronache saw in the optimizer theme that is possible to actually display the widget area where we need ( even with custom filters ) - https://www.evernote.com/l/AY_3LM6gYEBIzowY4euftfoUnJxkiY_A9Y4

It should be way better if we can do this for zerif lite/ pro

**Comment by rodica-andronache** [comment]
https://www.layerthemes.com/theme/optimizer/
