### ISSUE TITLE
google webmaster structured data missing author

### ISSUE THREAD

**Issue by rodica-andronache** [Codeinwp/zerif-lite#187]
https://secure.helpscout.net/conversation/114760986/43528/
https://wordpress.org/support/topic/magazine-basic-google-webmasters-tools-missing-updated-missing-author
https://wordpress.org/support/topic/google-structured-data-missing-elements-author-entry-title-updated

**Comment by tkes** [comment]
Would suggest to replace (reserved hatom class names)[http://microformats.org/wiki/hatom] like `entry-title`, `entry-content` and similar with own prefixed classnames like `zf-entry-title` and similar for theme CSS styling, so the hatom classnames can be removed/left out from page templates without impact on layout/style.

The use of hatom classnames is advised only for timeline-related content like articles/blog posts.

As soon as Google finds a reserved classname, they start to look for the other mandatory entries and this causes the errors on pages.

Adding hidden author/updated entries to pages is not a solution for this!

**Comment by rodica-andronache** [comment]
@tkes thanks for the suggestion! we will take it into consideration

**Comment by DsxDesigns** [comment]
I am experiencing the same issues with the markup. Specifically the updated tag needs to be fixed. In webmasters it shows as missing updated, and creates a mess of errors...

**Comment by rodica-andronache** [comment]
https://github.com/Codeinwp/zerif-pro/issues/414

**Comment by daileycon** [comment]
Any fixes for this? All pages I create give these errors in Google webmaster. 

Missing: author
Missing: updated
