### ISSUE TITLE
IBEDUCATOR Plugin Changed Appearance and Pages got black

### ISSUE THREAD

**Issue by kashif6331** [Codeinwp/zerif-lite#189]
I am using IBEducator Plugin and appearance of all pages (Courses & Lessons) is turned black that is not at all viewer friendly, rather annoying. Please help.

**Comment by rodica-andronache** [comment]
@kashif6331 thank you for reporting this issue. We will try to fix it in a future update.
Could you please let me know if this is the plugin you mentioned https://github.com/wp-plugins/ibeducator/ ?
