### ISSUE TITLE
sample data cant download

### ISSUE THREAD

**Issue by ozzedone** [Codeinwp/zerif-lite#190]
hello
when i click on link for sample data it shows me the data in my browser. doesnt let me down load the .xml file

am i missing something or is this not right?

http://dev2.themeisle.com/data/zeriflite.wordpress.2015-02-17.xml

thats the page that opens

thank you for your time

**Comment by rodica-andronache** [comment]
Hey @ozzedone ,

You mean you can't download it from here: http://themeisle.com/documentation-zerif-lite/ ?

**Comment by rodica-andronache** [comment]
Hello @ozzedone ,

From what I've tested the sample data file it's working ok at this moment, so I am going to close this issue. If you are still having trouble with this, please contact us on our support forum.

Thank you,
Rodica
