### ISSUE TITLE
add accesibility-ready tag

### ISSUE THREAD

**Issue by ineagu** [Codeinwp/zerif-lite#195]
@rodica-andronache ar trebui sa adaugam tag-ul asta si sa incercam sa trimitem un update sapt asta, reusim ?

Mai era la changelog si partea cu pluginul

**Comment by rodica-andronache** [comment]
@ineagu la plugin mai e ceva de lucru. Eu zic sa trimitem la inceputul saptamanii viitoare, ca nu cred ca termin saptamana asta. La changelog nu stiu la ce te referi
