### ISSUE TITLE
Remove wp_is_mobile()

### ISSUE THREAD

**Issue by rodica-andronache** [Codeinwp/zerif-lite#204]
wp_is_mobile() was added for parallax, why ? Is recommended not to use it, we need another solution

However, recommend you remove wp_is_mobile on next update as it should not
be used in themes
(https://codex.wordpress.org/Function_Reference/wp_is_mobile). See
https://core.trac.wordpress.org/ticket/26221 for explanation.

**Comment by rodica-andronache** [comment]
@ineagu they say we should use this: http://foundation.zurb.com/docs/components/visibility.html but this is only for hiding/showing elements on certain devices. I am not sure how we could use this to include certain js scripts for different devices.

**Comment by ineagu** [comment]
There are some js based solutions.

**Comment by rodica-andronache** [comment]
@ineagu can you please give me an idea here, because I can't find how to include a script in php, by detecting the device in js

**Comment by ineagu** [comment]
is not on the php side, is on js, like if screenwidth<x print script


On Thu, Oct 1, 2015 at 9:05 PM, Rodica-Elena Andronache <
notifications@github.com> wrote:

> @ineagu <https://github.com/ineagu> can you please give me an idea here,
> because I can't find how to include a script in php, by detecting the
> device in js
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Codeinwp/zerif-lite/issues/204#issuecomment-144818482>
> .
>



-- 
Ionut Neagu
http://themeisle.com | http://codeinwp.com | http://ionutn.com

**Comment by rodica-andronache** [comment]
@ineagu si cum fac asta, dar sa tina cont si de dependente de alte js-uri/css?

**Comment by ineagu** [comment]
enque_script ( x.js ) + dependinte etc

iar in x.js :

if ( screen<500 ) document.write (parallax.js )

Dar poti intreaba si tu pe stackoverflow la sectiunea wp, slack etc.

Oricum asta nu e o chestie blocanta pt update.

Sa imi zici cand pot face inca un review, mai poti ruga si pe altcineva sa
testeze


On Mon, Oct 5, 2015 at 9:30 PM, Rodica-Elena Andronache <
notifications@github.com> wrote:

> @ineagu <https://github.com/ineagu> si cum fac asta, dar sa tina cont si
> de dependente de alte js-uri/css?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Codeinwp/zerif-lite/issues/204#issuecomment-145512752>
> .
>



-- 
Ionut Neagu
http://themeisle.com | http://codeinwp.com | http://ionutn.com

**Comment by rodica-andronache** [comment]
@ineagu can I close this? It's not really easy to do, and I don't think it would bring us a real benfit right now

**Comment by rodica-andronache** [comment]
@ineagu did you see this?

**Comment by ineagu** [comment]
Yes
