### ISSUE TITLE
Pirate form with child theme

### ISSUE THREAD

**Issue by rodica-andronache** [Codeinwp/zerif-lite#206]
What is happening if a client reworked the contact form in a child theme ? Can you verify ? In this case we should his implementation, since probably contact form was modified

**Comment by rodica-andronache** [comment]
@ineagu dupa cum e facuta acum tema, ca sa-si modifice child theme-ul, ar fi trebuit sa modifice front-page.php in child theme, si asta ar insemna ca nu i se modifica nimic la update-ul la zerif lite, pt ca in front-page.php fac verificarea daca are pirate forms sau nu.
Dar nu inteleg cum o sa le mai functioneze celor cu child theme, daca noi la un update urmator, o sa scoatem de tot contact us section din customizer.

**Comment by ineagu** [comment]
pai nu avem treaba cu tema, din plugin nu putem verifica daca tema parinte
e zerif-lite , sau child responsive boat, si sectiunea in customizer nu
exista ? si e asa sa adaugam noi sectiunea in customizer si pe prima pagina
?

Presupun ca inainte ar trebui sa avem un hook in child-theme in zona aia ca
sa se poata baga plugin-ul acolo .

Iar la urmatorul update o sa scoatem codul din frontpage.php, chestia din
customizer ramane.

2015-10-05 21:12 GMT+09:00 Rodica-Elena Andronache <notifications@github.com
>:

> @ineagu <https://github.com/ineagu> dupa cum e facuta acum tema, ca sa-si
> modifice child theme-ul, ar fi trebuit sa modifice front-page.php in child
> theme, si asta ar insemna ca nu i se modifica nimic la update-ul la zerif
> lite, pt ca in front-page.php fac verificarea daca are pirate forms sau nu.
> Dar nu inteleg cum o sa le mai functioneze celor cu child theme, daca noi
> la un update urmator, o sa scoatem de tot contact us section din customizer.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Codeinwp/zerif-lite/issues/206#issuecomment-145508633>
> .
>



-- 
Ionut Neagu
http://themeisle.com | http://codeinwp.com | http://ionutn.com
