### ISSUE TITLE
Check theme size

### ISSUE THREAD

**Issue by rodica-andronache** [Codeinwp/zerif-lite#210]
can you also look more into sizes ? production branch has 1.3MB while development 3.2MB

**Comment by rodica-andronache** [comment]
@ineagu aici am ajuns la 2.2M pe dev. Nu stiu ce as putrea sa mai optimizez

**Comment by ineagu** [comment]
e ok

On Mon, Oct 5, 2015 at 9:07 PM, Rodica-Elena Andronache <
notifications@github.com> wrote:

> @ineagu <https://github.com/ineagu> aici am ajuns la 2.2M pe dev. Nu stiu
> ce as putrea sa mai optimizez
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Codeinwp/zerif-lite/issues/210#issuecomment-145507376>
> .
>



-- 
Ionut Neagu
http://themeisle.com | http://codeinwp.com | http://ionutn.com
