### ISSUE TITLE
Our Focus widget

### ISSUE THREAD

**Issue by rodica-andronache** [Codeinwp/zerif-lite#212]
You have added the widget areas in their corresponding place, however you should also try to filter/order the widgets in that space, for example if I wanna add an Our Focus widget, I wanna see that widget first, not to scroll in 50 widgets until I find it :)

**Comment by rodica-andronache** [comment]
@ineagu aici nu stiu daca e posibil (https://wordpress.org/support/topic/control-display-order-of-available-widgets-on-widgets-screen), sau si daca e, cred ca e destul de complicat. Las issue-ul deschis si poate reusesc la un moment dat :)

**Comment by rodica-andronache** [comment]
@ineagu can I close this, or should we still try? I don't think it's easy

**Comment by ineagu** [comment]
bine, inchide

On Thu, Apr 7, 2016 at 11:42 AM, Rodica-Elena Andronache <
notifications@github.com> wrote:

> @ineagu <https://github.com/ineagu> can I close this, or should we still
> try? I don't think it's easy
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/Codeinwp/zerif-lite/issues/212#issuecomment-206761987>
>



-- 
Ionut Neagu
http://themeisle.com | http://codeinwp.com | http://ionutn.com
