### ISSUE TITLE
Add video lock icon thing in big title section ( available in pro )

### ISSUE THREAD

**Issue by rodica-andronache** [Codeinwp/zerif-lite#217]

**Comment by rodica-andronache** [comment]
@ineagu aici nu am inteles exact la ce te referi. Sa pun in big title, faza de Video background, ca e available in pro?

**Comment by ineagu** [comment]
da, cu chestie din aia cu lacatel :D

On Tue, Sep 29, 2015 at 2:51 PM, Rodica-Elena Andronache <
notifications@github.com> wrote:

> @ineagu <https://github.com/ineagu> aici nu am inteles exact la ce te
> referi. Sa pun in big title, faza de Video background, ca e available in
> pro?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Codeinwp/zerif-lite/issues/217#issuecomment-144048748>
> .
>



-- 
Ionut Neagu
http://themeisle.com | http://codeinwp.com | http://ionutn.com
