### ISSUE TITLE
I have installed zerif lite latest version

### ISSUE THREAD

**Issue by rodica-andronache** [Codeinwp/zerif-lite#218]
, tried to send an email, got an error, installed pirate forms, tried to send an email says it was a success, but I didn't get an email . ( on qsandbox ), so obviously somewhere, something is wrong .

**Comment by rodica-andronache** [comment]
@ineagu aici stii cumva daca nu aveai setata adresa de email in customizer, in zerif lite? ca asta ma gandesc ca poate fi cazul in care ai testat tu.
Ca acum, daca e gol in customizer, de la zerif, pune adresa de email de la administrator, si de-asta probabil a zis ca a trimis (si probabil a fost considerat spam, de nu ai primit. ca daca nu pui text relevant cand faci test, si nu ai setat aia cu smtp, nu trimite mereu)

**Comment by rodica-andronache** [comment]
dar o sa modific , sa ia ce e in customizer. daca acolo e gol, sa fie gol si in pirate forms

**Comment by rodica-andronache** [comment]
https://github.com/Codeinwp/pirate-forms/commit/a19e47e0cada3164f6654756901ace080d8797e6

@ineagu acum pt cei care au downloadat deja pluginul, daca aveau totul lasat default, o sa aibe ceva probleme, in sensul ca nu o sa mai aiba adresa de email cum era inainte, daca nu o aveau setata din customizer in zerif. Dar nu cred ca e asa o problema, avand in vedere ca nu sunt nici 10 instalari,nu?

**Comment by ineagu** [comment]
putem presupune ca nu are nimeni pluginul :D

On Mon, Oct 5, 2015 at 8:52 PM, Rodica-Elena Andronache <
notifications@github.com> wrote:

> Closed #218 <https://github.com/Codeinwp/zerif-lite/issues/218>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Codeinwp/zerif-lite/issues/218#event-426689613>.
>



-- 
Ionut Neagu
http://themeisle.com | http://codeinwp.com | http://ionutn.com
