### ISSUE TITLE
When Pirate Forms is activated

### ISSUE THREAD

**Issue by rodica-andronache** [Codeinwp/zerif-lite#219]
When Pirate Forms is activated, we should use in the customizer section : Contact Us the details from Pirate Forms ( email, labels ), so we need to add some new fields and for existing make sure the content match the admin that exist now, so in case somebody add the captcha in pirate forms admin, this should be visible in customizer as well and backwards.

**Comment by rodica-andronache** [comment]
@ineagu aici nu am inteles ce vrei sa spui , cu, crearea unor noi campuri.
am inteles, ca gen, cand are activat pirate forms, ar trebui sa i se adauge si in customizer, ce modifica el in pirate forms

**Comment by ineagu** [comment]
Pai in customiEr nu exista labels de ex pt toate alea

**Comment by rodica-andronache** [comment]
@ineagu aici nu mai bine, cand are activat pirate forms, sa dau disable la sectiunea de contact din customizer? de fapt, sa las doar titlu si subtitlu, si sa pun un text in care sa zic, gen, ca trebuie sa se dupa la setarile Pirate Forms.
Si daca dezactiveaza pluginul, sa-i apara la loc sectiunea de contact.

**Comment by ineagu** [comment]
nu, mi se pare fain sa poate edita chestiile vizuale din customizer totusi,
si setarile principala, putem mentiona ca pt advanced settings sa se duca
 acolo .

2015-10-05 21:05 GMT+09:00 Rodica-Elena Andronache <notifications@github.com
>:

> @ineagu <https://github.com/ineagu> aici nu mai bine, cand are activat
> pirate forms, sa dau disable la sectiunea de contact din customizer? de
> fapt, sa las doar titlu si subtitlu, si sa pun un text in care sa zic, gen,
> ca trebuie sa se dupa la setarile Pirate Forms.
> Si daca dezactiveaza pluginul, sa-i apara la loc sectiunea de contact.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Codeinwp/zerif-lite/issues/219#issuecomment-145506977>
> .
>



-- 
Ionut Neagu
http://themeisle.com | http://codeinwp.com | http://ionutn.com
