### ISSUE TITLE
Search field widget design

### ISSUE THREAD

**Issue by orschiro** [Codeinwp/zerif-lite#238]
Dear all, 

I have noticed a slightly misaligned search field widget. 

![image](https://cloud.githubusercontent.com/assets/170947/10856063/690b4748-7f45-11e5-9ee6-ded1a282ecfe.png)

To be seen live here: http://scorai.org/jobs/

Can someone confirm this or is this probably some plugin incompatibility on my side?

Thankfully,

Robert

**Comment by rodica-andronache** [comment]
@orschiro I think it's something to do with this plugin: https://wordpress.org/plugins/buttons-shortcode-and-widget/ Can you please try to deactivate it and see if this was the problem?

Thank you,
Rodica

**Comment by orschiro** [comment]
Dear @rodica-andronache,

You're absolutely right! Thank you!

Unfortunately this is a very useful plugin. 

Do you know an alternative or a solution to make it compatible with zerif-lite?

Thankfully,

~ Robert

**Comment by rodica-andronache** [comment]
@orschiro you can try to install https://wordpress.org/plugins/simple-custom-css/ and in Appearance -> Custom CSS add this piece of code:
.widget_search input { -webkit-box-sizing: initial !important; }
Please let me know if that helps the problem.

Thank you,
Rodica

**Comment by orschiro** [comment]
Dear @rodica-andronache,

It fixed the problem. Thank you very much for your support!

~ Robert

**Comment by rodica-andronache** [comment]
Happy to help!
