### ISSUE TITLE
Undefined index: open_new_window

### ISSUE THREAD

**Issue by alexgff** [Codeinwp/zerif-lite#239]
I get PHP Notice:  Undefined index: open_new_window in wp-content\themes\zerif-lite\functions.php on line 1057.
WordPress 4.3.1
Zerif Lite version: 1.8.2.6
All plugins are deactivated

**Comment by HardeepAsrani** [comment]
Did you install the theme using FTP?

**Comment by alexgff** [comment]
@HardeepAsrani 
update from WP dashboard

**Comment by HardeepAsrani** [comment]
Instead of Github, please send all the details about the issue at friends@themeisle.com and we will assist you with this issue.

Because if it's not an issue with the theme, but only with one user then we will have to investigate first. :)

**Comment by HardeepAsrani** [comment]
@alexgff 

We've fixed this and will be up with the next release: https://github.com/Codeinwp/zerif-lite/pull/242
