### ISSUE TITLE
The called constructor method for WP_Widget is deprecated since version 4.3.0! Use  __construct()

### ISSUE THREAD

**Issue by loorlab** [Codeinwp/zerif-lite#240]
Hi, Zerif Lite Warning -->
Notice: The called constructor method for WP_Widget is deprecated since version 4.3.0! Use

__construct()

instead. in /path/wp-includes/functions.php on line 3457

**Comment by rodica-andronache** [comment]
@loorlab this problem was fixed in the last version. Please update, and let me know if everything is ok

**Comment by loorlab** [comment]
@rodica-andronache We had to restore the database because wp_options data is erased of our installation, updating the Theme Zerif Lite, but something strange and update the theme and everything going well, thank you.
