### ISSUE TITLE
How to disable Archives widget?

### ISSUE THREAD

**Issue by orschiro** [Codeinwp/zerif-lite#246]
Dear all, 

I'm having some trouble disabling/removing the Archives widget. 

Please take a look at this example page:

http://scorai.org/teaching/

As you can see, the Archives and META widgets are displayed on this example page although the sidebar widget settings are empty:

![image](https://cloud.githubusercontent.com/assets/170947/10992994/a54d8cb8-846b-11e5-9386-af181c672140.png)

Could someone give me a hint how I can remove these two widgets?

Thankfully,

~ Robert

**Comment by HardeepAsrani** [comment]
Hi,

Try adding an empty Text widget to your sidebar to solve this. :)

Regards,
Hardeep

**Comment by orschiro** [comment]
Dear @HardeepAsrani,

It did work. Thanks!

~ Robert
