### ISSUE TITLE
Footer icons padding issue

### ISSUE THREAD

**Issue by orschiro** [Codeinwp/zerif-lite#248]
Dear all,

We use custom icons in the footer. 

With one of the recent theme updates, however, the icon's padding to the text has decreased significantly. 

Currently it looks as follows:

![image](https://cloud.githubusercontent.com/assets/170947/11029375/ddca9010-86c6-11e5-9529-3c4ea1b43acb.png)

Source: http://scorai.org/

Can someone confirm this? 

Thankfully

~ Robert

**Comment by rodica-andronache** [comment]
Hi @orschiro ,

I think you either made some customization to the theme, or it's a conflict with a plugin.
To fix your issue, you could use https://wordpress.org/plugins/simple-custom-css/ and in Appearance -> Custom CSS add this:
.company-details .icon-top {display:block !important;}
Please let me know if this helps.

**Comment by orschiro** [comment]
Dear @rodica-andronache,

> .company-details .icon-top {display:block !important;}

You helped me fixing this issue. Thank you very much!

For now I will stick with it until I've found which plugin is causing an issue. 

~ Robert

**Comment by rodica-andronache** [comment]
Glad to be able to help :)
