### ISSUE TITLE
Remove chilld theme's descriptions

### ISSUE THREAD

**Issue by rodica-andronache** [Codeinwp/zerif-lite#249]
La zerif lite la welcome page, am putea scoate descrierea la child themes. E mult de tradus
La fel titlurile articolelor catre docs le-as pune sa nu poata fi traduse, oricum articolele sunt in engleza, ce zici? Poti intreba pe slack themerrview

**Comment by ineagu** [comment]
@claudiuvertistudio you can remove those .
