### ISSUE TITLE
Add a Header opacity option

### ISSUE THREAD

**Issue by rodica-andronache** [Codeinwp/zerif-lite#255]

**Comment by claudiuvertistudio** [comment]
@ineagu  it is necessary to add option for transparency on the layer of big title?

**Comment by rodica-andronache** [comment]
the option it's already in the pro version

**Comment by ineagu** [comment]
don't think so, not sure how many people really want it. Otherwise we can
write a small tutorial on how you can do it with css

On Fri, Apr 29, 2016 at 11:07 AM, Claudiu Buruiana <notifications@github.com
> wrote:

> @ineagu <https://github.com/ineagu> it is necessary to add option for
> transparency on the layer of big title?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/Codeinwp/zerif-lite/issues/255#issuecomment-215664531>
>



-- 
Ionut Neagu
http://themeisle.com | http://codeinwp.com | http://ionutn.com

**Comment by ineagu** [comment]
ok, so ?

On Fri, Apr 29, 2016 at 11:08 AM, Rodica-Elena Andronache <
notifications@github.com> wrote:

> the option it's already in the pro version
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/Codeinwp/zerif-lite/issues/255#issuecomment-215664760>
>



-- 
Ionut Neagu
http://themeisle.com | http://codeinwp.com | http://ionutn.com

**Comment by claudiuvertistudio** [comment]
This is an option for pro. why to add in lite version?

**Comment by ineagu** [comment]
we don't need to add it.

On Fri, Apr 29, 2016 at 11:14 AM, Claudiu Buruiana <notifications@github.com
> wrote:

> This is an option for pro. why to add in lite version?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/Codeinwp/zerif-lite/issues/255#issuecomment-215665710>
>



-- 
Ionut Neagu
http://themeisle.com | http://codeinwp.com | http://ionutn.com
