### ISSUE TITLE
Automatic text spacing

### ISSUE THREAD

**Issue by rjdevries** [Codeinwp/zerif-lite#258]
![spacing](https://cloud.githubusercontent.com/assets/967586/11481021/1f192402-979b-11e5-98fb-3772f6b60725.png)
Hi, thanks for the greal theme.
There is one think I would like to disable. And that is the automatic text spacing. As you can see, it can make the page ugly.
Can you please tell me how to disable it?

Thanks. 

Greetings, Ronald de Vries

**Comment by rodica-andronache** [comment]
HI @rjdevries,

Thank you for the kind words about Zerif. Could you please give me the link to your website so I can give you a solution?

Thank you,
Rodica

**Comment by rjdevries** [comment]
Hi Rodica,

Yes of course!  http://rjdev.nl/ron/about/
The best way to see what I mean is to scale the page to about 680px.
Hopefully you see what I mean and understand my point.

Thanks again.
Greetings, Ronald de Vries

**Comment by rodica-andronache** [comment]
Hi Ronald,

You can try to install this plugin https://wordpress.org/plugins/simple-custom-css/: 
go to Appearance -> Custom CSS add this:

.entry-content p {
    text-align: inherit !important;
}

Regards,
Rodica

**Comment by rjdevries** [comment]
Work like a charm, Thanks!

Regards, Ronald

2015-12-02 20:02 GMT+01:00 Rodica-Elena Andronache <notifications@github.com

**Comment by rodica-andronache** [comment]
Great to hear that!
