### ISSUE TITLE
1.8.3.2 Introduced escaping errors for HTML entered in Customizer 

### ISSUE THREAD

**Issue by jsmcgraw** [Codeinwp/zerif-lite#279]
With 1.8.3.2, some HTML characters entered into the Customizer dialog are being printed as text instead of code. < and > are the most notable problems, for obvious reasons, though I haven't observed any others. Other users are starting to notice this now:

https://wordpress.org/support/topic/html-in-customizer-now-being-printed-to-screen?replies=4

**Comment by rodica-andronache** [comment]
Hi @jsmcgraw ,

Thank you for contacting us. Yes, in the latest update we changed some parts of the escaping, but we'll release an update very soon to fix the issues mentioned.

Best regards,
Rodica

**Comment by rodica-andronache** [comment]
Hi @jsmcgraw ,
I just wanted to let you know that we just released the new update , and sent it to wordpress.org for review. It will probably be live in the next couple of days. If you don't want to wait for the update, you can always download the theme from here: https://github.com/Codeinwp/zerif-lite, and replace the files in your theme.
After you update to the new version, please let us know if everything is ok.

Thank you,
Rodica

**Comment by rodica-andronache** [comment]
Hi @jsmcgraw ,

The update is live now. Could you please let us know if everything is ok now?

Thank you,
Rodica

**Comment by jsmcgraw** [comment]
Looks good, thanks.
