### ISSUE TITLE
HTML support in About us > Feature No

### ISSUE THREAD

**Issue by orschiro** [Codeinwp/zerif-lite#282]
Dear all, 

Is it possible that something changed with the HTML support in `About us > Feature No`?

I recall that I was able to add HTML elements (e.g. <a>) there. 

But now they no longer seem to be supported and rendered. 

Please see the below screenshot.

Thankfully,

~Robert

![image](https://cloud.githubusercontent.com/assets/170947/12288791/8e529250-b9d7-11e5-8801-3f5f686ad977.png)

**Comment by rodica-andronache** [comment]
Hi @orschiro ,

Yes, we did some changes on escaping, but due to various complaints from our users, we decised to allow html tags back. We'll release an update as soon as possible.

Thank you,
Rodica

**Comment by orschiro** [comment]
Hi @rodica-andronache,

That's great news, thank you!

I will wait for the update then. 

~Robert

**Comment by rodica-andronache** [comment]
Hi @orschiro  ,
I just wanted to let you know that we just released the new update , and sent it to wordpress.org for review. It will probably be live in the next couple of days. 
After you update to the new version, please let us know if everything is ok.

Thank you,
Rodica

**Comment by orschiro** [comment]
Dear Rodica, 

That's great news. Thanks!

**Comment by rodica-andronache** [comment]
Hi @orschiro ,

The update is live now. Could you please let us know if everything is ok now?

Thank you,
Rodica

**Comment by orschiro** [comment]
Dear @rodica-andronache,

I received the update today and HTML code is working again. 

Thank you so much!

~Robert

**Comment by rodica-andronache** [comment]
Hi @orschiro ,

I am really happy to hear that. Let us know if we can help you with anything else.
I will close this issue now.

Best regards,
Rodica
