### ISSUE TITLE
HTML support in Customizing > Big title section > Main content > Title [text field]

### ISSUE THREAD

**Issue by steve-ee** [Codeinwp/zerif-lite#283]
Hi there,

@orschiro wrote in issue 282, escaping changes made, received complaints from users, and are allowing HTML tags. 

Does this update include HTML support in Customizing > Big title section > Main content > Title [text field]? HTML support was available before version: 1.8.3.2.

Kind regards, 
steve-ee

![html-issue-01](https://cloud.githubusercontent.com/assets/16694137/12311960/14ea711e-bac0-11e5-832d-f74724e3ae61.jpg)

**Comment by rodica-andronache** [comment]
Hi @steve-ee ,

In the update we are currently working to release, we'll try to allow html tags in as all the sections our users want to add it. So, it will also be available for the Big title section.
If you don't want to wait until the update will go live, you can use the previous version you can download from here: https://github.com/Codeinwp/zerif-lite/tree/production. You would need to replace your theme files with the ones downloaded.

Best regards,
Rodica

**Comment by steve-ee** [comment]
Cheers for the update.

Steve-ee


Kind regards ... Steve Eades
M: +64 274 424 132

**Comment by rodica-andronache** [comment]
Hi @steve-ee,

I just wanted to let you know that we just released the new update , and sent it to wordpress.org for review. It will probably be live in the next couple of days. 
After you update to the new version, please let us know if everything is ok.

Thank you,
Rodica

**Comment by rodica-andronache** [comment]
Hi @steve-ee ,

The update is live now. Could you please let us know if everything is ok now?

Thank you,
Rodica

**Comment by steve-ee** [comment]
Hi there,

Yes everything looks fine so far. Will let you know if find anything.

Cheers, Steve-ee
