### ISSUE TITLE
HTML Support in Ribbon Sections > BottomButton Ribbon/RightButton Ribbon > Text [Text Field] 

### ISSUE THREAD

**Issue by bill-m-wang** [Codeinwp/zerif-lite#284]
As of 1.8.3.2 the escaping changes removed HTML support for various text sections. This results in previously working code like <br> simply printing out the text instead of creating a new line break.
![bottombutton_ribbon_html](https://cloud.githubusercontent.com/assets/16695966/12314543/39acf192-bac6-11e5-8ce4-202a64ba4598.png)
As @orschiro wrote in issue 282 HTML support was added to the "About Us" section. Are there any plans to add support to the ribbon sections?

**Comment by rodica-andronache** [comment]
Hi @bill-m-wang ,
Thank you also for letting us know about the issue.
Yes, we'll add support for HTML in the ribbons sections too in the update we are currently working on. And if you want, until we release the update, you can also use the previous version, from here: https://github.com/Codeinwp/zerif-lite/tree/production. You could download the files, and replace the ones you have now.

Best regards,
Rodica

**Comment by rodica-andronache** [comment]
Hi @bill-m-wang ,
I just wanted to let you know that we just released the new update , and sent it to wordpress.org for review. It will probably be live in the next couple of days. 
After you update to the new version, please let us know if everything is ok.

Thank you,
Rodica

**Comment by rodica-andronache** [comment]
Hi @bill-m-wang,

The update is live now. Could you please let us know if everything is ok now?

Thank you,
Rodica

**Comment by bill-m-wang** [comment]
Hello,
I've updated the theme and it appears to work fine now, thank you for the quick update.
