### ISSUE TITLE
How to change "Leave a Reply" text?

### ISSUE THREAD

**Issue by orschiro** [Codeinwp/zerif-lite#292]
Dear all,

I am struggling to find the correct template to change the text "Leave a Reply" that is shown above the comment box. 

May someone help me?

Thankfully,

~Robert

**Comment by rodica-andronache** [comment]
Hi @orschiro ,

You can try to follow this documentation : http://docs.themeisle.com/article/190-zerif-how-to-change-the-leave-a-reply-text.
Let us know what you think and if we can help you with anything else.

Best regards,
Rodica

**Comment by orschiro** [comment]
Hi @rodica-andronache,

Thanks for sharing the link to your documentation!

Unfortunately I don't have access to the FTP server. Do you have any idea how I could create the file `functions.css` from within the WP Admin?

Thankfully,

~Robert

**Comment by rodica-andronache** [comment]
Hi @orschiro ,

To make the child theme, you would need access to FTP, so in this case the only suggestion would be to change the theme files like this:

In comments.php change:

`<?php comment_form(array('comment_notes_after' => '')); ?>`

to:

`<?php comment_form(array('comment_notes_after' => '','title_reply'       => __( 'New text' ),'title_reply_to'    => __( 'New text %s' ))); ?>`

But you need to be aware that this changes would be lost everytime you update the theme. So, you either don't update it in the future, or make this change after every update.

Regards,
Rodica

**Comment by orschiro** [comment]
Dear @rodica-andronache,

It finally did work out, thank you so much for your help!

I managed to get access to our FTP server and thus could easily create the child theme and `functions.css` following your documentation. 

It all looks good now except for the fact that suddenly our top logo banner bar colour changed and the logo became smaller (is that due to using a child theme?).

But I guess that's another unrelated issue?

**New:**

![image](https://cloud.githubusercontent.com/assets/170947/12535821/76e6d808-c290-11e5-913c-90a2ad350f86.png)


**Old:**

![image](https://cloud.githubusercontent.com/assets/170947/12535819/7107e35a-c290-11e5-81a3-5adbca405e54.png)


Source: [scorai.org](http://scorai.org/)

**Comment by rodica-andronache** [comment]
Hi @orschiro ,

I think it has something to do with the way you created the child theme files. Could you let me know what is the content of the functions.php file from your child theme?

Thank you,
Rodica

**Comment by orschiro** [comment]
Hi @rodica-andronache,

I very appreciate your willingness to help me!

This is the content of functions.php:

```
<?php
// Exit if accessed directly
if ( !defined( 'ABSPATH' ) ) exit;

// BEGIN ENQUEUE PARENT ACTION
// AUTO GENERATED - Do not modify or remove comment markers above or below:

        
if ( !function_exists( 'chld_thm_cfg_parent_css' ) ):
    function chld_thm_cfg_parent_css() {
        wp_enqueue_style( 'chld_thm_cfg_parent', trailingslashit( get_template_directory_uri() ) . 'style.css' );
    }
endif;
add_action( 'wp_enqueue_scripts', 'chld_thm_cfg_parent_css' );

if ( !function_exists( 'chld_thm_cfg_child_css' ) ):
    function chld_thm_cfg_child_css() {
        wp_enqueue_style( 'chld_thm_cfg_child', get_stylesheet_uri() ); 
    }
endif;
add_action( 'wp_enqueue_scripts', 'chld_thm_cfg_child_css', 999 );

// END ENQUEUE PARENT ACTION
```

I assume this file was automatically created by [Child Theme Configurator](https://wordpress.org/plugins/child-theme-configurator/) which I used to create the child theme initially.

**Comment by orschiro** [comment]
Dear @rodica-andronache and others, 

I managed to solve the child theme issue. For future reference, these are the working settings:

![image](https://cloud.githubusercontent.com/assets/170947/12580076/e6e35b7a-c42c-11e5-9ad1-a09cab0446c0.png)

Thankfully,

~Robert

**Comment by rodica-andronache** [comment]
Hi @orschiro,

Thanks for letting us know about that. Maybe it will help others that use the Child Theme Configurator plugin to create a child theme.

Best regards,
Rodica
