### ISSUE TITLE
Full Width Page without sidebar widgets?

### ISSUE THREAD

**Issue by orschiro** [Codeinwp/zerif-lite#295]
Dear all, 

For one of our pages I set the template to `Full Width Page` in the expectation that this would hide the sidebar widgets. However, as you can see in the below screenshot, they are still shown. 

Can you advise me how to proceed?

Thankfully,

~Robert

![image](https://cloud.githubusercontent.com/assets/170947/12676629/f91ffce4-c693-11e5-9583-92b2f06f9404.png)

**Comment by rodica-andronache** [comment]
Hi @orschiro ,

That should not happen. Are you using the latest version of the theme?
Also, could you please give me the link to that page so I can investigate?

Thank you,
Rodica

**Comment by orschiro** [comment]
Hi @rodica-andronache,

It's this page: http://scorai.org/teaching/course-descriptions/

Zerif LIte is `Version: 1.8.3.3`.

Thanks!

~Robert

**Comment by rodica-andronache** [comment]
Hi @orschiro ,

I checked your page, and there are two issues there. First, you don't seem to have selected the full page template, and second one, you are using dataTables on that page, and at some times, when you load the page, you get a pop up error from that script, so I think there is a problem of how that script is used.
Let me know what you think.

Regards,
Rodica

**Comment by orschiro** [comment]
Dear @rodica-andronache, 

I am sorry. I think you are right. My error is completely unrelated to the theme. 

I double checked that "Full Width" is actually selected and indeed now it works (despite the other error). 

Sorry for causing noise...

~Robert
