### ISSUE TITLE
"Our Happy Clients" divider showing when adding widget to About section

### ISSUE THREAD

**Issue by mulvak** [Codeinwp/zerif-lite#301]
When adding any widget to the "About Us Section" then the "About Us Section" pullout (usually nothing here) what looks like a section divider shows up with text "Our Happy Clients" (see below.)  This one just happens to be the Testimonial Widget, but it happens with all of them.

![about section](https://cloud.githubusercontent.com/assets/17504926/13367117/f34cd35e-dc83-11e5-859d-51b46ea0a5e1.PNG)

**Comment by rodica-andronache** [comment]
Hi @mulvak thank you for contacting us. Yes, that section was created especially for the Clients widgets, and that is why the default Our Happy clients appears. Unfortunately changing that text is not available in Zerif Lite, but in the pro version, Zerif PRO.
