### ISSUE TITLE
Option to Display Sticky posts in the latest news section

### ISSUE THREAD

**Issue by rodica-andronache** [Codeinwp/zerif-lite#302]
https://wordpress.org/support/topic/sticky-post-not-showing-1

**Comment by ineagu** [comment]
Adding an option for this is bad, since the theme is popular and we can't just do that change, we can create a docs for it, we don't add an option just for this super mega simple and useless thing.

**Comment by rodica-andronache** [comment]
ok, I'll add it in the docs pipeline and close this
