### ISSUE TITLE
possible vulnerability

### ISSUE THREAD

**Issue by rodica-andronache** [Codeinwp/zerif-lite#306]
It allows global variables to be inserted. Look here: zerif-lite/inc/extras.php

**Comment by rodica-andronache** [comment]
@ineagu I can't remember what was this about. Do you?

**Comment by ineagu** [comment]
It allows global variables to be inserted. Look here: zerif-lite/inc/extras.php :)) cred ca e suficient

**Comment by rodica-andronache** [comment]
duplicate of https://github.com/Codeinwp/zerif-lite/issues/338
