### ISSUE TITLE
Recommended plugins  & tutorials

### ISSUE THREAD

**Issue by ineagu** [Codeinwp/zerif-lite#308]
@rodica-andronache  We should add SiteOrigin + ECPT as recommended plugins and link to this doc : http://docs.themeisle.com/article/219-how-to-build-a-landing-page-with-a-drag-and-drop-content-builder

**Comment by rodica-andronache** [comment]
@ineagu ECPT should be linked to our site: http://themeisle.com/plugins/easy-content-types/ ? Because I don't think we can add an install button like on the other plugins, from wp.org

And should we remove some of the other recommended plugins? I think right now, there are two many

**Comment by ineagu** [comment]
Yes, and yes we can remove some that are not making sense
