### ISSUE TITLE
bug affects the loading of zerif.js

### ISSUE THREAD

**Issue by alexandrastann** [Codeinwp/zerif-lite#310]
https://wordpress.org/support/topic/bug-in-zerifjs-file?replies=1#post-8128410

**Comment by cristian-ungureanu** [comment]
@rodica-andronache , I can't replicate this issue, was this fixed? The code seems fine to me. I tested this on all versions that were released in march and didn't find anything.

**Comment by rodica-andronache** [comment]
@cristian-ungureanu I couldn't replicate this either, but maybe there was a certain case when this happened. Maybe we can also add here 

`if ( thisOpen == false && (typeof jQuery('.contact-form textarea').val() != 'undefined') && (jQuery('.contact-form textarea').val().length > 0) ) {`

another condition too , like 
`if ( thisOpen == false && (typeof jQuery('.contact-form textarea') != 'undefined') && (jQuery('.contact-form textarea').length > 0) && (typeof jQuery('.contact-form textarea').val() != 'undefined') && (jQuery('.contact-form textarea').val().length > 0) ) {`

something like this. You can test if it's ok
