### ISSUE TITLE
Big title section in mobile view?

### ISSUE THREAD

**Issue by orschiro** [Codeinwp/zerif-lite#315]
Dear all,

The concerned website is [scorai.org](http://scorai.org/).

When viewed mobile, it shows the latest blog posts. However, I would like it to show the big title section.

Any ideas how to achieve it?

Thankfully,

~Robert

**Comment by rodica-andronache** [comment]
Hi @orschiro ,

This does not have anything to do with the theme. I think it's a plugin that's causing this, maybe Jetpack, I think it has a mobile option that you need to disable or something like this.
Please let me know if you manage to do that.
Regards,
Rodica

**Comment by orschiro** [comment]
Dear @rodica-andronache,

As always great support. 

Thank you so much!

The solution was to [deactivate the mobile Jetpack module](http://jetpack.com/support/mobile-theme/).

Warmly,

~Robert

**Comment by rodica-andronache** [comment]
Hi @orschiro ,

I am really glad I could help you.
If you are happy with our theme and support, you can always leave us a review here: https://wordpress.org/support/view/theme-reviews/zerif-lite#postform . It would help us a lot.

Thank you,
Rodica

**Comment by orschiro** [comment]
Dear Rodica,

I just submitted my edited review.

I thank you for all your hard work!

Warmly,

~Robert
