### ISSUE TITLE
Issues in custimization

### ISSUE THREAD

**Issue by sevedge28** [Codeinwp/zerif-lite#326]
When I am working on the site in customize everything is fine, but nothing is changing over to my actual website. I am making sure to save and apply all changes. But nothing is changing for the actual page outside of customization.

**Comment by sevedge28** [comment]
Now my home screen is coming up blank. Train-To-Thrive.com

**Comment by rodica-andronache** [comment]
Hi @sevedge28,

Have you managed to fix the issue? I can see the site running.

Thank you,
Rodica

**Comment by sevedge28** [comment]
I just hopped on and fixed it. My issue was with the template of the pages. Thank you.

**Comment by rodica-andronache** [comment]
@sevedge28 can you please give me more details about the issue so I can check?

Thanks

**Comment by sevedge28** [comment]
When I was customizing my front page, on numerous occasions I would save it, but when I opened a new tab and loaded the page, only the big section had changed, the our focus and down had not updated, even though I have made the changes.

I'm honestly not quite sure why it fixed all of the sudden.

**Comment by rodica-andronache** [comment]
@sevedge28 ok, thank you. In this case, I will have to close this issue. If you encounter any other issue, please let us know.
