### ISSUE TITLE
Warning: Illegal string offset 'zerif_logo'

### ISSUE THREAD

**Issue by urfusion** [Codeinwp/zerif-lite#329]
Whenever try to update anything getting error for example when updating logo getting below error

> <b>Warning</b>:  Illegal string offset 'zerif_logo' in <b>/wp-includes
> /theme.php</b> on line <b>902</b><br />
> {"success":true,"data":[]}

**Comment by HardeepAsrani** [comment]
Which version of Zerif are you using

**Comment by urfusion** [comment]
I am using Zerif Lite V 1.8.4.0.

On Sun, Apr 10, 2016 at 12:44 PM, Hardeep Asrani <notifications@github.com>
wrote:

> Which version of Zerif are you using
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/Codeinwp/zerif-lite/issues/329#issuecomment-207937749>
>



-- 
With Regards
Kapil Kr. Sharma
Kadam Technologies Pvt. Ltd.
+91-9414357848

**Comment by urfusion** [comment]
I am using Zerif Lite V 1.8.4.0.

**Comment by rodica-andronache** [comment]
Hi @urfusion ,

Could you please give us also your site URL? Also, did you use FTP to install the theme to your server?

Thanks

**Comment by urfusion** [comment]
@rodica-andronache  : How can I provide you details?

**Comment by rodica-andronache** [comment]
Hi @urfusion ,

You can post here your site URL.

**Comment by urfusion** [comment]
http://kadams.in/clinic/

**Comment by rodica-andronache** [comment]
Hi @urfusion ,

Thank you for the URL.
You didn't answered to this question: "did you use FTP to install the theme to your server"

**Comment by urfusion** [comment]
Hello,

Yes,First I locally install it then upload to server. On local system it is
working fine.

On Wed, Apr 27, 2016 at 6:19 PM, Rodica-Elena Andronache <
notifications@github.com> wrote:

> Hi @urfusion <https://github.com/urfusion> ,
>
> Thank you for the URL.
> You didn't answered to this question: "did you use FTP to install the
> theme to your server"
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/Codeinwp/zerif-lite/issues/329#issuecomment-215071540>
>



-- 
With Regards
Kapil Kr. Sharma
Kadam Technologies Pvt. Ltd.
+91-9414357848

**Comment by rodica-andronache** [comment]
Hi @urfusion ,

If you installed it using FTP, this most likey is the cause of your issue. You should read this document about this: http://docs.themeisle.com/article/23-parse-error-syntax-error-on-upload-theme-plugin.
Let me know if you manage to fix this.

Regards,
Rodica

**Comment by urfusion** [comment]
Thanks,
I will try that.

**Comment by urfusion** [comment]
I deleted all the theme files under `/wp-content/themes/zerif-lite` and install it again by wp add new theme option and still my changes are not reflecting.

on ajax call I am getting {"success":false}

**Comment by rodica-andronache** [comment]
Hi @urfusion ,

Then maybe it's a conflict with some plugin. Have you tried deactivating all the plugins?

Regards,
Rodica

**Comment by urfusion** [comment]
Just install child theme and it is working fine. But same issue is with main theme. I have only theme required extensions.

**Comment by rodica-andronache** [comment]
We didn't encountered this issue before. If you said that on local everthing was working fine, maybe there is  something wrong with the servers settings. You could try to see if the issue appears for other themes too.

Regards,
Rodica

**Comment by urfusion** [comment]
Core themes are working fine with no issue. I need to check that with other themes. I will check and let you know.
