### ISSUE TITLE
Change demo images for shop page

### ISSUE THREAD

**Issue by rodica-andronache** [Codeinwp/zerif-lite#330]

**Comment by ineagu** [comment]
can we somehow just import the images /products from zerif pro DEMO ? :D

**Comment by mileamadalin** [comment]
@rodica-andronache Aici ma ocup acum de ele. Chestia este ca trebuie sa le adaug din nou si pe versiunea pro si apoi pe lite. Cumva s-au sters toate si noroc cu Cloudinary pentru ca le pot recupera de acolo si adauga. Te anunt cand este gata.

**Comment by mileamadalin** [comment]
@rodica-andronache este gata. poti verifica

**Comment by rodica-andronache** [comment]
@mileamadalin mersi frumos :)
