### ISSUE TITLE
Error: Syntax error, unrecognized expression: #site-navigation a[href*=#]:not([href=#]), header.header a[href*=#]:not([href=#])

### ISSUE THREAD

**Issue by loorlab** [Codeinwp/zerif-lite#332]
Hi Friends, with upgrade WP 4.5 display the following error : 

Error: Syntax error, unrecognized expression: #site-navigation a[href_=#]:not([href=#]), header.header a[href_=#]:not([href=#]) on --> jquery.js?ver=1.12.3

Thanks !

**Comment by HardeepAsrani** [comment]
Yes, it's an issue with I just saw 15 mins ago. We will fix it by the end of the day. :)

**Comment by HardeepAsrani** [comment]
@loorlab Are you using the latest version? This is happening with few of our themes but Zerif Lite isn't the one. It's working properly in it.

**Comment by loorlab** [comment]
@HardeepAsrani HI, our version --> Version: 1.8.2.5 
Our Site : http://www.waveloor.com/

Thanks !

**Comment by rodica-andronache** [comment]
Hi @loorlab ,

The latest version of Zerif Lite is 1.8.4.0. Please update and let us know if everything is ok.
Thanks

**Comment by rodica-andronache** [comment]
Hi @loorlab ,

I'm going to close this issue, as is not part of the latest version of the theme.

**Comment by loorlab** [comment]
Thanks @rodica-andronache We update the template and effectively error is no longer displayed.

**Comment by smartcville** [comment]
I'm in 1.8.4.1 and getting the same error.  Error: Syntax error, unrecognized expression: #site-navigation a[href*=#]:not([href=#]), header.header a[href*=#]:not([href=#])
