### ISSUE TITLE
Pixeden icons are not there

### ISSUE THREAD

**Issue by mizanplus** [Codeinwp/zerif-lite#334]
@selu91 Where is the icons for pixeden defined in stylesheet  zerif-lite/css/pixeden-icons.css ?" Can you elaborate the purpose of the icons?

**Comment by selu91** [comment]
@rodica-andronache what do you think about this ?

**Comment by rodica-andronache** [comment]
Hi @ezer0 ,

The pixeden-icons.css file was an old one, that we somehow forgot to delete even though was not used. In the next update of Zerif Lite, we'll remove it.
Thank you for letting us know about this.
Regards,
Rodica
