### ISSUE TITLE
"Our Team" section links

### ISSUE THREAD

**Issue by tarababcock** [Codeinwp/zerif-lite#340]
Is there any way to add a link to a page anchor or url using a team member photo? I would like to be able to click on the photo and have it link back to the page anchor/url in the "about us" section of the primary menu to be able to read a larger bio about each employee. Thank you.

**Comment by nicolasFernandez** [comment]
were you able to do this? I have the same problem here.

**Comment by tarababcock** [comment]
No, sorry.

**Comment by rodica-andronache** [comment]
Hi,

We have an option for a link in the Our Team widgets, in the PRO version, but we'll add this option in Zerif Lite too, in one of the next updates.

Thank you,
Rodica

**Comment by smehrjerdian** [comment]
Was this ever released in Zerif lite? There has to be a way to do this without paying for the upgraded version. I am running responsive boat which is a child of Zerif lite and I know there has to be a way to link those images without paying for an pro version

**Comment by smehrjerdian** [comment]
I am attempting to link the “our team” images on the home-page to a separate page on the site by using JQuery and a Custom JavaScript plugin.

I have added the following code to the plug-in

$(“#zerif_team-widget-1 img”).wrap(“‘);

The images don’t have ID’s so the next closest unique ID I targeted was the span ID “Zerif_team-widget-1” the images are nested in and than I added the “img” to try to target the img inside the span.

based on feedback I saw in this stack-overflow article: https://stackoverflow.com/questions/2400218/add-link-to-image-dynamically

But when I save it and go to my site it doesn’t fire and I see this error in my console:

Uncaught SyntaxError: Invalid or unexpected token

And it points to the index.php file

Not sure if any of this makes sense, I am fairly new to programming, any help would be appreciated and I really would prefer not to get the paid version if I don’t need it

The page I need help with: http://gypsysoultattooparlor.com/
