### ISSUE TITLE
Problem with author display on page?

### ISSUE THREAD

**Issue by orschiro** [Codeinwp/zerif-lite#341]
Dear all,

I'm a bit irritated with the way the author name is being displayed on a page:

![image](https://cloud.githubusercontent.com/assets/170947/15172971/8136ed98-1759-11e6-8a97-f9d622ca68b3.png)

Live: http://scorai.org/login/

It looks as if something was missing here. 

Can this be a problem of my child theme or a general problem with the theme?

Thankfully,

~Robert

**Comment by rodica-andronache** [comment]
Hi @orschiro,

I am not really sure why the issue appeared on your site (something added an extra class to the body element) but we fixed this case from the theme and the update we are working to release will fix this. Let us know if this is not the case.

Thank you,
Rodica

**Comment by orschiro** [comment]
Hi @rodica-andronache,

Thank you so much for the fix. 

I can confirm that it is working. :smiley: 

~Robert

**Comment by rodica-andronache** [comment]
Hi @orschiro ,

I am really happy to know everything is ok now:)

Best regards,
Rodica

**Comment by ineagu** [comment]
@rodica-andronache the solution here isn't ok, probably you are overriding a plugin setting : https://wordpress.org/support/topic/author-name-in-page-showing-even-thow-it-says-display-none?replies=1

**Comment by orschiro** [comment]
Thanks for raising this problem @ineagu!

Indeed, now the author name is no longer being displayed on post pages:

http://scorai.org/stream/newsletter-june-2016/

~Robert

![image](https://cloud.githubusercontent.com/assets/170947/15709195/b66b38b0-2803-11e6-8c66-7b4b92abb089.png)
