### ISSUE TITLE
Update tgmp

### ISSUE THREAD

**Issue by rodica-andronache** [Codeinwp/zerif-lite#342]
http://tgmpluginactivation.com/2016/05/15/tgmpa-2.6.0-released/

**Comment by abaicus** [comment]
Fixed in https://github.com/Codeinwp/zerif-lite/commit/b747ffc0bf7bcd8697cd7879f7d590383685660c .

**Comment by abaicus** [comment]
@ineagu 
 aici avem ca problema un bug al celor de la TGMPA. Au niste chestii puse aiurea in clasa si iese un link pe tabelul de install. Cu el arata nasol:

**Comment by ineagu** [comment]
nu vad nimic. Poti raporta bug-ul la ei

**Comment by abaicus** [comment]
![image](https://cloud.githubusercontent.com/assets/15010186/15362076/a322c59e-1d1c-11e6-96f7-37da6d8b17ab.png)


Si pot sa il fac sa arate normal. Presupun ca trebuia sa fie scos numele pluginului.

![image](https://cloud.githubusercontent.com/assets/15010186/15362166/f822a212-1d1c-11e6-948d-c5cad9998301.png)

**Comment by abaicus** [comment]
Mi-au zis sa le iau varianta de pe dev ca au rezolvat issue-ul.

**Comment by abaicus** [comment]
Updated and fixed issues in b747ffc0bf7bcd8697cd7879f7d590383685660c | 8b96a00cf0d13b475ebbb4d763953c3b049947a1 .
