### ISSUE TITLE
Improving quotes?

### ISSUE THREAD

**Issue by orschiro** [Codeinwp/zerif-lite#344]
Dear all, 

What do you think of improving quotes and making them more explicitly visible?

Just to give you one example:

![image](https://cloud.githubusercontent.com/assets/170947/15564207/f0c9d2b2-230f-11e6-8055-5b3adcaac7d5.png)

From my perspective it could be made more clear what is a quote and what not.

Thus not only by indenting the text but maybe by adding a visual quotation mark or background box around the text.

What do you think?

Thankfully,

~Robert

**Comment by rodica-andronache** [comment]
Hi @orschiro ,

Thank you for you feedback.
We'll take this in consideration and hopefully find the best solution for all the users :)

Best regards,
Rodica

**Comment by UVLabs** [comment]
+1

**Comment by HardeepAsrani** [comment]
How's this but orange? ![Quotes](http://independentpublisher.me/wordpress/wp-content/uploads/2013/11/Screen-Shot-2013-11-30-at-11.40.07-AM.png)

**Comment by orschiro** [comment]
@HardeepAsrani, 

this is great! 

-Robert

**Comment by rodica-andronache** [comment]
@HardeepAsrani this is how it looks now http://prntscr.com/cfxv48
it doesn't look like you said, because of the font I guess. Can you please check

**Comment by HardeepAsrani** [comment]
@rodica-andronache I kept it that way. Let me know if you wanna change the fonts or size. :)

**Comment by rodica-andronache** [comment]
@HardeepAsrani I changed the font myself. Sorry, but we needed to update now

**Comment by orschiro** [comment]
@rodica-andronache thank you so much for incorporating this into the next release! :-)

Warmly,

-Robert

**Comment by orschiro** [comment]
Hi @orschiro ,

Thank you for you feedback.
We'll take this in consideration and hopefully find the best solution for  
all the users :)

Best regards,
Rodica

---
