### ISSUE TITLE
Issue with image uploader in widgets

### ISSUE THREAD

**Issue by suyogyashukla** [Codeinwp/zerif-lite#349]
If I had multiple widgets and select an image to any of of them, it triggers the change in all the widgets.
See [this thread.](https://wordpress.org/support/topic/the-image-field-in-multiple-our-focus-widgets-are-all-linked-together)
Thanks!

**Comment by suyogyashukla** [comment]
@rodica-andronache

**Comment by UVLabs** [comment]
@rodica-andronache the browser console spits out the error when you click "Insert into post"

**Comment by HardeepAsrani** [comment]
@rodica-andronache We should just remove the option to insert from Media Library until we find a solution. We can see other image widgets for a better solution.

**Comment by rodica-andronache** [comment]
@cristian-ungureanu thanks :)
