### ISSUE TITLE
Font Awesome quote marks in Testimonials not showing

### ISSUE THREAD

**Issue by veromary** [Codeinwp/zerif-lite#351]
If I edit functions.php and change:
<i class="icon-fontawesome-webfont-294"></i>
to
<i class="fa fa-left-quote"></i>
then the quote marks come up as in the screenshots.

**Comment by HardeepAsrani** [comment]
What do you mean? Could you give us more details?

**Comment by veromary** [comment]
Here is how it looked as installed:
![withoutquotemarks](https://cloud.githubusercontent.com/assets/1920800/15984539/41d76ba6-3012-11e6-9c92-9bbd8b4fa517.png)

Here is how it looked once I made the changes above (I think it's line 958 of functions.php)
![withquotemarks](https://cloud.githubusercontent.com/assets/1920800/15984538/41d63b96-3012-11e6-8775-f7077a8ee303.png)

**Comment by veromary** [comment]
Oh, I see my code is invisible.

I changed this:
```
<i class="icon-fontawesome-webfont-294"></i>
```

to this:
```
<i class="fa fa-quote-left"></i>
```

**Comment by HardeepAsrani** [comment]
@veromary Yup, it appears to be an issue. We will fix it in an upcoming release. Thanks for reporting! :)

**Comment by rodica-andronache** [comment]
@ineagu what do you think it's best here? The icon is not showing in zerif lite since a lot time (even though in zerif pro is appearing), and if we add it now, maybe not everybody will be happy. You think it's ok to fix it now or to add an option (for quote icon or not) ?

**Comment by ineagu** [comment]
Just fix it
