### ISSUE TITLE
Button links in Big Title Section disappear

### ISSUE THREAD

**Issue by jackmaley** [Codeinwp/zerif-lite#352]
When I change the button link address to point to a page inside the site the button disappears.  Tried pointing to a post and it still doesn't work.  Not sure what I'm doing wrong.

**Comment by rodica-andronache** [comment]
Hi @jackmaley ,

Thank you for contacting us. I tried to replicate your issue. Could you please give me more details like your site URL and whether or not you are using the latest version of the theme? Also, have you tried deactivating all your plugins?

Thank you,
Rodica

**Comment by jackmaley** [comment]
ivimedia.com/2016
Hosted on HostGator
ZerifLite v 1.8.4.4
Latest Wordpress, all plugins deactivated
MacPro Late 2013 running 10.11.5
Chrome

I screen grabbed the problem ... https://m3.wistia.com/medias/89hv0gvnk4






Jack Maley
m3
1133 Broadway Suite 1319
New York, NY 10010
212 366 6123
getm3.com

**Comment by jackmaley** [comment]
THanks, R!  I'll check out that issue too.  Appreciate the help!

**Comment by rodica-andronache** [comment]
Ok Jack, 

I will now close this issue, but please do let us know if you still need help with this.

Best Regards

**Comment by jackmaley** [comment]
I just converted my website page URL to a bit.ly URL and that fixed the problem.  Weird ... it didn't like my website page URL!

**Comment by rodica-andronache** [comment]
Weird indeed..maybe after the child theme is updated you can let us know if you still have issues with normal URL
