### ISSUE TITLE
Mention that video backgrounds do not work on mobile

### ISSUE THREAD

**Issue by UVLabs** [Codeinwp/zerif-lite#353]
From customizer I believe you could view the video background in mobile view. But they do not actually work on mobile phones because of what I mentioned here: https://github.com/Codeinwp/zerif-pro/issues/496 we should say that somewhere in customizer.

**Comment by HardeepAsrani** [comment]
@UVLabs Video background isn't available in Pro, therefore closing this. Will add the info to the Pro. Thanks! :)
