### ISSUE TITLE
Footer Social Icons: YouTube?

### ISSUE THREAD

**Issue by orschiro** [Codeinwp/zerif-lite#358]
Dear all, 

What do you think of adding YouTube to the footer social icons? :smiley: 

Thankfully,

~Robert

![image](https://cloud.githubusercontent.com/assets/170947/16410775/5b8f3460-3d24-11e6-9fad-01f9de6ed6e7.png)

**Comment by rodica-andronache** [comment]
Hello @orschiro ,

Zerif PRO has an Youtube option http://prntscr.com/bmkh8t. If you want to use Zerif Lite, you can follow this doc http://docs.themeisle.com/article/8-adding-new-social-icons-to-zerif-footer to create a new option.

Regards,
Rodica

**Comment by orschiro** [comment]
Thank you @rodica-andronache!

I very appreciate that there is an option for Zerif Lite users. 

Thankfully,

~Robert
