### ISSUE TITLE
New Section: Video Section

### ISSUE THREAD

**Issue by mariusghitulescu** [Codeinwp/zerif-lite#36]
Nu am foarte multe detalii pentru sugestie, dar fiind o pagina de prezentare, o sectiune pentru video-uri ar fi foarte utila, unde utilizatorii sa poata da embedd la video-uri de pe Youtube/Dailymotion.
Cum nu toti au cunostinte avansate, cred ca ar fi util sa fie embedd automat, sa bage doar link-ul sau ID-ul video-ului.

Poate si un checkbox pentru Embed On/Off, pentru cei ce doresc sa bage tot codul de embedd si nu doar link-ul/id-ul de pe YT/Dailymotion. Astfel nu am limita sectiunea doar la cele anumite retele site-uri, si ar putea adauga orice (exemplu: embed la un joc in flash)

**Comment by ineagu** [comment]
@rodica-andronache asta am putea mai degraba face in pro nu ? de ce dai closed  ? :D

**Comment by rodica-andronache** [comment]
@ineagu pai am pus issue pt versiunea pro. De asta am dat close aici :)
