### ISSUE TITLE
Bad Alignment of "Features" icons on Tablet

### ISSUE THREAD

**Issue by diegeo** [Codeinwp/zerif-lite#360]
When you add more than 4 "Features" (in my case I have 8), on a tablet you see that rows 3 and 4 (corresponding to the features 5 to 8 in my case) are not vertically aligned with the first four features (not even between themselves).

**Comment by rodica-andronache** [comment]
Hi @diegeo ,

Could you please give me more details about this, so we can further investigate, like your site URL and the tablet device you are using to test the theme?

Thank you,
Rodica

**Comment by diegeo** [comment]
Hi Rodica,
I just downloaded the theme yesterday and installed on my PC, and noticed
this when adding the "features" on the tablet preview. Please see the image
attached.

Cheers!
Diego

**Comment by rodica-andronache** [comment]
Hi Diego,

I'm not able to see the attached image. Could you please try again?

Thanks,
Rodica

**Comment by diegeo** [comment]
Hi Rodica,
I just can't insert the file here, I tried changing extension and different browsers but nothing (and it's 78 Kb only!). Anyway, the bug it's very simple to replicate. Just go on Wordpress to Appearence --> Customize --> Our Focus Section --> Our Focus Section Widgets. There click on Add a Widget  and select Zerif - Our Focus Widget, and complete the fields with any info. If you add 1 or 2 of those and are previewing the site as a tablet you will see that the new widgets added are not aligned with the first 4 that originally came. Hope that helps!
Cheers,
Diego

**Comment by rodica-andronache** [comment]
Hi Diego,

This is how it looks for me on an Ipad http://prntscr.com/bomqj3. The alignment seems ok.
You can use a Chrome extension like this for example https://chrome.google.com/webstore/detail/lightshot-screenshot-tool/mbniclmhobmnbdlbpiphghaielnnpgdp?hl=en to send me a screenshot of the issue.

Regards,
Rodica

**Comment by diegeo** [comment]
Hi Rodica,
I used the extension and here is how it looks for me with 8 icons:
http://prntscr.com/bownk1
I don't know if you are viewing it in landscape mode or you have a bigger
tablet because I can only see 2 icons in a row, which I believe is OK for
small tablets. Look that after the second row, the consecutive ones are not
aligned not even between themselves. I'm running version 1.8.2.5 of Zerif.
Cheers,
Diego

**Comment by rodica-andronache** [comment]
Hi Diego,

Are you using a child theme of Zerif? Or have you done any customizations to Zerif?

Regards,
Rodica

**Comment by diegeo** [comment]
Hi,
I'm not using a child theme, just took out a few sections and changed the
code for converting circles to squares (code provided by themeisle).

Cheers

**Comment by rodica-andronache** [comment]
Hi Diego,

I've tried, but I'm not able to replicate this. Could you please give me your site URL so I can see the issue?

Thank you,
Rodica

**Comment by rodica-andronache** [comment]
Hi Diego,

Are you still having this issue? Could you please give us your site URL?

Thank you,
Rodica

**Comment by rodica-andronache** [comment]
Hi Diego ,

I will have to close this, as there was no answer for almost a month, and we couldn't replicate this, but if you still have issues you can contact us here http://themeisle.com/contact/.

Thank you,
