### ISSUE TITLE
The size of textarea boxes in the customizer section

### ISSUE THREAD

**Issue by HappyDoggie** [Codeinwp/zerif-lite#361]
Hi, 
I love this theme and appreciate that I am using this theme to build a website now. 

I don't have any issues with this theme, but I am just wondering if you could expand the textarea box size in the customer section.  I tried to expand them, modifying wpglobus-config.json, but it did not work.  

Thank you so much. 

Luna

**Comment by rodica-andronache** [comment]
Hi @HappyDoggie ,

I'm really happy to hear you like our theme. Regarding your issue, I am not sure I understand what you mean. You want to expand in height boxes like this http://prntscr.com/bomo14 ? Because this has nothing to do with the wpglobus-config.json file.

Regards,
Rodica

**Comment by rodica-andronache** [comment]
Hi @HappyDoggie ,

Could you please post an update here so we can investigate?

Thank you,
Rodica
