### ISSUE TITLE
Bugs in Post

### ISSUE THREAD

**Issue by bwfrazer1** [Codeinwp/zerif-lite#363]
I have been writing a post and in the preview I am getting this
1. H2 headings are not showing (only 2 of 6 are visible)
2. H3 Headings are not formatting (3 of 6 are formatted)
3. At the beginning of Post it appears that 2 columns are created
4. using current WP 
   5, ZERIF LITE theme is up to date
5. any other posts are not affected on the site
   my site is http://www.marketerproductreviews.com  
   The preview page is
   http://www.marketerproductreviews.com/?p=104&preview=true
   time is of the essence in publishing this review ...

thanks

Bruce Frazer

**Comment by rodica-andronache** [comment]
Hello Bruce,

Thank you for contacting us.
Could you please give me more details about how was the content added in the post? Did you used the default wordpress editor, or did you used something like a page builder?

Regards,
Rodica

**Comment by rodica-andronache** [comment]
Hi @bwfrazer1 ,

Any update on this?

Thank you,
Rodica

**Comment by rodica-andronache** [comment]
Hi @bwfrazer1 ,

I will close this, as there is no answer for more then 20 days and I couldn't replicate this, but if you still have issues you can contact us here : http://themeisle.com/contact/

Thanks
