### ISSUE TITLE
Theme Review

### ISSUE THREAD

**Issue by grappler** [Codeinwp/zerif-lite#364]
I was looking at the theme and found the following issues.
- [x] Enqueue html5.js and ie.css, or least load via the functions.php - This may cause issues with child themes that have copied the header.php
- [x] Move `zerif_old_render_title` to the functions.php - same here as above.
- [x] Replace `$wp_customize` with `is_customize_preview`
- [ ] Prefix image sizes `add_image_size` - This should be possible with an update script.
- [x] Define jquery as a dependancy instead of loading on its own
- [ ] `wp_is_mobile()` does not work well with caching.
- [ ] Text not internationalized in `zerif_register_default_widgets`
- [x] Load the script on the widget admin pages `zerif_ourfocus_widget_scripts`
- [x] `$instance['link'];` in `widget()` should be escaped
- [ ] Update TGMP What was the issue here: https://github.com/Codeinwp/zerif-lite/commit/4f343091a0e4abb92700f6b3c77fba76b8aa46b3
- [x] Escape `$zerif_lite_review` in `zerif_lite_asking_for_reviews_script`

**Comment by UVLabs** [comment]
@rodica-andronache @claudiuvertistudio
