### ISSUE TITLE
Front Page & Blog page (rel=next and rel=prev) problems

### ISSUE THREAD

**Issue by mitchellkrogza** [Codeinwp/zerif-lite#366]
Hi folks, I love Zerif but like all modern templates it has a big problem when it comes to Yoast's SEO plugin and even Wordpress Core seem to have problems with it. 

I really hope somebody can help with this problem.

If you set Wordpress > Reading > to "Your Latest Posts" (needed to have Zerif work properly)
Yoast SEO plugin see's the front page as paged. 

If you look in the source code of the page it has 

`<link rel="next" href="https://my.website.com/page/2/">`

If you take this link 
`https://my.website.com/page/2/ 
`and paste it into your browser you will see it takes you right back to the front page, except now, if you look in the source code it will have the following.

```
<link rel="prev" href="https://my.website.com">
<link rel="next" href="https://my.website.com/page/3/">
```

Once again, if you take the link ending in /page/3/ it does the same thing except you now have

```
<link rel="prev" href="https://my.website.com/page/2/">
<link rel="next" href="https://my.website.com/page/4/">

```

It keeps doing this for as long as you can keep going. For SEO this is very bad, because you are telling a search engine like Google there is multiple pages and when it goes to look (which it does) it see's they are all the same and you could be penalized for trying to push out duplicate content.

SO .... That problem is EASILY solved by simply having this empty function called genesis in your child themes functions.php

`function genesis {}
`

A Quick Simple fix and it immediately takes the rel=next and rel=prev links out of the front page.

The next problem is however a little more tricky and rather annoying.

In order to have a blog page that shows our posts, we create a page called 'blog' and assign it to one of the blog templates. In my case template-blog.php

The problem now, is that even though the blog page shows "Older Posts" and "Newer Posts" links at the bottom of the page, Yoast's SEO plugin can not see that this page is "paged". Yoast see's the page as a single page entity and will therefore NOT add the rel=next and rel=prev links.

For some reason the page is declaring itself to Wordpress and Yoast as a single page and not an archived or paged entity.

I have spent hours trying to fix it myself an I came pretty close but it's not perfect nor is it the right way either. My knowledge of the Wordpress core is scary so this was a real hack on my part and really not the proper solution but I had to forge ahead with migrating my site to Zerif and this was holding me back.

To get the rel=next and prev links to appear on the page called "blog" I copied the header.php file from zerif into my child theme and added this code which took me hours to fiddle with and figure out.

```
if ( is_page('blog')){
echo "<!-- BEGIN Custom Rel Links -->\n";
$paged = (get_query_var('paged')) ? get_query_var('paged') : 1;
$whatis = get_previous_posts_link();

    if ( empty($whatis) ) { 
      ?>
        <link rel="next" href="<?php echo get_pagenum_link( $paged + 1 ); ?>">
        <meta name="robots" content="noodp"/>
    <?php
    } 
else {
?>
    <link rel="prev" href="<?php echo get_pagenum_link( $paged - 1 ); ?>">
    <link rel="next" href="<?php echo get_pagenum_link( $paged + 1 ); ?>">
    <meta name="robots" content="noodp"/>
  <?php
}
echo "<!-- END Custom Rel Links -->\n";
}

```

This works perfectly .... except for when I get to my last page of my blog Page 28. That's where it now adds 

```
<link rel="prev" href="https://my.website.com/blog/page/27/">
<link rel="next" href="https://my.website.com/blog/page/29/">

```

and of course I do not have a page 29 .... so the problem just continues.

There really has to be some solid fix to this and I am out of ideas and time with my knowledge of the wordpress core and why this is even happening in the first place.

Please can someone restore my sanity and tell me how to fix this for good and also correctly.

**Comment by rodica-andronache** [comment]
Hi @mitchellkrogza ,

Thank you very much for contacting us and letting us know about this. We'll investigate this issue and let you know about it.

Regards,
Rodica

**Comment by mitchellkrogza** [comment]
Thanks so much Rodica, I anxiously look forward to hearing from you, I 
want to put Zerif into full swing but that is holding me back. Also 
tested 17 other templates from other template designers who all want you 
to set the wordpress to "your latest posts" and they all do the same 
thing. Zerif is however still the best one yet as far as features and 
looks goes.

Kind Regards
Mitchell

**Comment by mitchellkrogza** [comment]
Hi Rodica

Any update on this yet?

**Comment by HardeepAsrani** [comment]
@mitchellkrogza @rodica-andronache I was thinking of patching it but the issue is... WP.org doesn't allow you to add any function without the theme name being its prefix. :/

**Comment by HardeepAsrani** [comment]
@mitchellkrogza And you can avoid adding an extra next link in the end with something like this:

```
<?php
$paged = get_query_var( 'paged' );

if ( $paged < $wp_query->max_num_pages ) {
?>
	 <link rel="prev" href="<?php echo get_pagenum_link( $paged - 1 ); ?>">
<?php } ?>
```

**Comment by HardeepAsrani** [comment]
And found the proper fix to remove it.

For the second issue, do you think the theme should add prev/next rel links? @rodica-andronache 

Pull coming for the first issue. :)

**Comment by ineagu** [comment]
for 2nd issue I don't think we need to add next/prev for frontpage.

**Comment by HardeepAsrani** [comment]
Thought so. We can create a doc about it maybe. :)

**Comment by mitchellkrogza** [comment]
Thank you Hardeep, I see a new update came out for Zerif Theme. I will test it out and see if it addresses the problems I was having.

**Comment by rodica-andronache** [comment]
Hi @mitchellkrogza ,

The update containing this fix is not yet live. We are still working on some issues and will release the update next week.

Thank you,
Rodica

**Comment by HardeepAsrani** [comment]
@mitchellkrogza If you wanna do it now then you can apply this: https://github.com/HardeepAsrani/zerif-lite/commit/eb08872a3fb15c1a6beddcd91ffb6347e4bcd0f1
