### ISSUE TITLE
Test with WP 4.6

### ISSUE THREAD

**Issue by mileamadalin** [Codeinwp/zerif-lite#369]
@HardeepAsrani  Could you please check if Zerif Lite is compatible with WordPress 4.6?

If everything is okay just let us know by writing "compatible", if not please add all issues here because in that way is easier for us to check them and then we can create issues for each one.

**Comment by HardeepAsrani** [comment]
- [ ] Not really an issue but the following warning appears on Console which isn't happening with other themes:

`22:16:47.892 Empty string passed to getElementById().1 jquery.js:2:24932`

**Comment by HardeepAsrani** [comment]
Everything else works just fine.

**Comment by rodica-andronache** [comment]
@HardeepAsrani I can't see those warnings. are you sure are caused by the theme? or maybe it's a conflict with a plugin?

**Comment by HardeepAsrani** [comment]
@rodica-andronache First one could be an issue with the jQuery + it's not appearing now even with the plugins active.

And second issue is still there.

**Comment by HardeepAsrani** [comment]
Second issue appears in the backend.
