### ISSUE TITLE
No option to change clients area title

### ISSUE THREAD

**Issue by UVLabs** [Codeinwp/zerif-lite#371]
There is an option in Zerif Pro to change the clients area title, but not in Lite, was this intentional? @rodica-andronache @claudiuvertistudio 

Zerif lite: http://prntscr.com/c0vafw

Zerif Pro: http://prntscr.com/c0vb0u

**Comment by HardeepAsrani** [comment]
@UVLabs Yea, kind of. :)

**Comment by rodica-andronache** [comment]
@UVLabs yes, but if you think that adding this in the lite version too, would bring a great improvement or make many users happy or something like that, make we can add it, as it's not something big

**Comment by UVLabs** [comment]
@rodica-andronache I think we should have it in the lite version, currently it's just static text the pro version has much more highlighted features than this small customization which I've seen two users ask for so far

**Comment by HardeepAsrani** [comment]
I made a commit to fix this but my Git is replacing the entire js file (whitespace issue) so should I send it?

**Comment by rodica-andronache** [comment]
@HardeepAsrani yes, you can. But it would be great if you also attach a screenshot of the changes, as you did on zerif pro
