### ISSUE TITLE
Customizer Links

### ISSUE THREAD

**Issue by rodica-andronache** [Codeinwp/zerif-lite#395]
Themes are allowed one top-level link in the customizer. This link should be done using the customizer API and not injected into the DOM via JavaScript.

**Comment by abaicus** [comment]
Is there still anything that needs to be done here?

**Comment by abaicus** [comment]
I mean if we should remove the locked sections from the customizer pannels. 
![image](https://cloud.githubusercontent.com/assets/15010186/18200638/6fb71a7a-710e-11e6-96f3-d503b7a94ffa.png)
![image](https://cloud.githubusercontent.com/assets/15010186/18200643/78f07366-710e-11e6-87b8-5f094b1d3af2.png)

**Comment by abaicus** [comment]
@rodica-andronache @ineagu

**Comment by ineagu** [comment]
nop
