### ISSUE TITLE
Jetpack and Photon Issue

### ISSUE THREAD

**Issue by UVLabs** [Codeinwp/zerif-lite#398]
I once saw an issue and @HardeepAsrani recommended turning off photon to fix it. But I think we should fix the conflict. Here's a post on the issue: https://wordpress.org/support/topic/what-is-the-content_width-on-zerif?replies=1

@rodica-andronache

**Comment by HardeepAsrani** [comment]
Interesting. Are we Gavin that issue on full width pages?

**Comment by HardeepAsrani** [comment]
I will investigate this and will let you know. Thanks!

**Comment by rodica-andronache** [comment]
@HardeepAsrani are you going to investigate this? can i assign it to you? 
Also, what that "Gavin" means? :D

**Comment by HardeepAsrani** [comment]
@rodica-andronache It meant "having" but my phone's autocorrect thought differently. And you can assign it to me.

**Comment by HardeepAsrani** [comment]
Umm, got it. Pull request is on its way for both Lite/Pro.

**Comment by rodica-andronache** [comment]
@HardeepAsrani can you please help to test this. I didn't understand how to replicate the issue
