### ISSUE TITLE
No author metadata in blog posts

### ISSUE THREAD

**Issue by UVLabs** [Codeinwp/zerif-lite#399]
There's no author metadata in the theme single posts:

http://prntscr.com/ccc5dj

But there is in Zerif Pro @rodica-andronache

**Comment by rodica-andronache** [comment]
@UVLabs I know this, but I'm not sure how it's better. In Zerif Lite the author metadata appears in the code (for google search tools), it just has display: none. I know that not all the users wanted those to appear (in the past), just wanted to be compliant with the search engines, so I added those just in the code.

And, I'm not sure if it would be a good  idea to suddenly display those texts. I think the best idea would be to have a doc (with some simple css, display: block etc)
What do you think?

**Comment by UVLabs** [comment]
Ok ill create a doc

**Comment by rodica-andronache** [comment]
@UVLabs was the doc created? can you please close this, when it's done? Thanks :)

**Comment by UVLabs** [comment]
@rodica-andronache no It hasn't, sure I will, I will add it to redbooth to remember

**Comment by rodica-andronache** [comment]
@UVLabs ok, please close this when it's done :) and also add the link of the doc

**Comment by UVLabs** [comment]
Done
