### ISSUE TITLE
Apply siteorigin styles only if siteorigin template used

### ISSUE THREAD

**Issue by UVLabs** [Codeinwp/zerif-lite#402]
@rodica-andronache I've seen so far that many users use siteorigin on regular pages without using the siteorigin template, so they wonder why the text is so close to the nav bar.

I think it's best we only apply the styles which remove the top padding and similar styles only when the site origin template is used.

**Comment by rodica-andronache** [comment]
yes, I've seen that too. We'll investigate and try to fix this

**Comment by rodica-andronache** [comment]
@claudiuvertistudio shouldn't this be added to all the style used for site origin maybe http://prntscr.com/cooxwn ?
