### ISSUE TITLE
Rename siteorgin template

### ISSUE THREAD

**Issue by UVLabs** [Codeinwp/zerif-lite#403]
@rodica-andronache so it's in sync with Zerif Pro: 

https://github.com/Codeinwp/zerif-lite/blob/production/template-fullwidth-no-title.php#L3

https://github.com/Codeinwp/zerif-pro/blob/production/template-fullwidth-no-title.php#L3

**Comment by rodica-andronache** [comment]
@UVLabs we can't do this right now, as it's messing up the translations on wp.org
