### ISSUE TITLE
 RTL ready issue

### ISSUE THREAD

**Issue by mileamadalin** [Codeinwp/zerif-lite#405]
@rodica-andronache @ineagu we have an issue with the RTL on Zerif Lite and Pro. When the theme uses the Arabic language the logo has the wrong position. 

[Request.pdf](https://github.com/Codeinwp/zerif-lite/files/458520/Request.pdf)

Please see the attached pdf. It has the original screenshot and a second screenshot for how it should be.

**Comment by rodica-andronache** [comment]
here we should investigate how is correct in RTL to have the logo , on the right or on the left. Maybe check some popular examples

**Comment by mileamadalin** [comment]
@rodica-andronache I think the correct way is as we do. I saw some examples and the correct way is with the logo on the right side. You can see some example as well here: https://www.drupal.org/node/977396

I think we can close this ticket.

**Comment by rodica-andronache** [comment]
@mileamadalin ok then, you can maybe create a doc, for users like the one who reported this, if you think it would help

**Comment by mileamadalin** [comment]
@rodica-andronache I think, maybe we can create a saved reply. Don't need a doc

**Comment by rodica-andronache** [comment]
whatever you guys think it's better :)
