### ISSUE TITLE
Can image captions be made more pretty?

### ISSUE THREAD

**Issue by orschiro** [Codeinwp/zerif-lite#416]
Dear all, 

I would like to ask you whether you can think of ways to make image captions a bit more pretty?

Currently, they look as follows.

Thankfully,

-Robert

![image](https://cloud.githubusercontent.com/assets/170947/18608619/c2e2bfd8-7cee-11e6-94fc-c69bca1bdff4.png)

**Comment by Basilakis** [comment]
Hey Robert,

Thanks a lot for letting us know that and for the suggestion.
Do you have any inspiration examples, that you think they are good?

Also those are the Captions at portfolio blocks?

Thanks a lot

**Comment by rodica-andronache** [comment]
Hi @orschiro ,

Are you using the latest version? Because in the latest version, we added some padding to image captions as you can see here https://github.com/Codeinwp/zerif-lite/blob/production/CHANGELOG.md

Regards,
Rodica

**Comment by orschiro** [comment]
Hi @Basilakis and @rodica-andronache,

Thanks for your feedback!

- I like the way it's done on [Medium](https://medium.com/@zephoria/there-was-a-bomb-on-my-block-6045e597ac2f#.lz47oyayv). No borders around the image and the caption colour in light grey.
- I am using the latest version of the theme that is available to me via the theme repository. 

Warmly,

-Robert

![image](https://cloud.githubusercontent.com/assets/170947/18698769/0719ea9c-7fcd-11e6-923f-3155546c3055.png)
![image](https://cloud.githubusercontent.com/assets/170947/18698772/0d3c612a-7fcd-11e6-9004-653fe1f69043.png)

**Comment by rodica-andronache** [comment]
Hi @orschiro ,

There are two issues here:

First, if you want the captions to look that way, you would need to use a custom code in a child theme, or using a css plugin like https://fr.wordpress.org/plugins/advanced-css-editor/. You would need to add this code:
`.wp-caption {
    border: none !important;
}
.wp-caption .wp-caption-text {
  text-align: center !important;
  color: rgba(0,0,0,.6) !important;
}`

Second, if you have the version 1.8.4.9 of the theme, it means you didn't found out yet, the sad news that Zerif was removed from the wordpress.org repository, and to further receive updates , you need to first update the theme from our site. To do that you need to follow this doc http://docs.themeisle.com/article/462-how-to-update-zerif-lite-from-themeisle . Please let me know if you need help with that.
Also, if you want to read more about the reason why Zerif Lite was removed , here is a full article about it https://codeinwp.com/blog/transparency-report-19/.

Regards,
Rodica

**Comment by orschiro** [comment]
@rodica-andronache,

You're doing great work. I really appreciate that transparency and honesty!

All problems solved. 

Thank you! :-)

-Robert

**Comment by rodica-andronache** [comment]
Hi Robert,

I'm really glad to hear that, we are doing our best to make great products and have happy users. Let us know if we can help with anything else.

Regards,
Rodica
