### ISSUE TITLE
Our Team Widget bug

### ISSUE THREAD

**Issue by ghost** [Codeinwp/zerif-lite#435]
Hi,

I have a blog that uses Zerif Lite and starting with 2.0.3 and still with 2.0.4, the Our Team widget used to cascade rows of widgets 2 deep and populate across the rest of the page. At present the widgets only populate vertically so a total of 7 widgets we were using displays in one vertical row instead of 3 plus 1. This makes the section very large and looks very unsuitable when seen. Let me know if I can send a snapshot some where to show you the effect we see.

Thanks!!

**Comment by rodica-andronache** [comment]
Hi Andrew,

Thank you for contacting us. If you could give us your site URL it would help us a lot, to investigate the issue.

Regards,
Rodica

**Comment by Andrew415** [comment]
I would do so but I have privacy issues of doing so on github, do you have a support email?

**Comment by rodica-andronache** [comment]
Hi Andrew,

You can contact us here http://themeisle.com/contact/.

Regards,
Rodica
