### ISSUE TITLE
Bug in hooks

### ISSUE THREAD

**Issue by HardeepAsrani** [Codeinwp/zerif-lite#436]
Details can be found here: https://wordpress.org/support/topic/bug-in-use-ofzerif_before_latest_news-hook/

Basically some hooks are being used on multiple locations.

**Comment by rodica-andronache** [comment]
I think we need to remove zerif_before_latest_news_trigger and zerif_after_latest_news_trigger from section/latest_news.php as it's already called in front-page.php
