### ISSUE TITLE
Wporg suspension fixes

### ISSUE THREAD

**Issue by ineagu** [Codeinwp/zerif-lite#437]
@rodica-andronache @selul We got some positive feedback for a series of fixes that we can do to make sure that we can have the theme in the repo, but do not affect existing users, here is a list of things that we need to fix, on a separate branch : 
- [ ] Remove contact form + recaptcha
- [x] The theme must use the core WordPress custom-logo feature. It also cannot display a default logo. Instead, show the user's site title.
- [x] The archive title and description must be output using the_archive_title() and the_archive_description() core functions.
- [x] This image is broken when using a child theme. From functions.php:
  'default-image' => get_stylesheet_directory_uri() . "/images/bg.jpg",
- [x] wp_title() back-compat
- [ ] Demo content needs to be removed from the front end
- [x] Deprecate the blog templates by removing the Template Name from the header as previously suggested https://themes.trac.wordpress.org/ticket/24907#comment:29
- [x] Automatically creating and saving widgets needs to be removed zerif_register_default_widgets
- [ ] Create a companion plugin to load widgets from the plugin 1st, while keeping them in the theme as well and encourage users to install the plugin
- [x] Remove locked sections and top level notices, do as we do for shopisle
  Fix FrontPage settings:  
- [ ] - Rename all customizer settings by adding _2 at the end and copy the content from normal_customizer
- [ ] - in front-page.php, verify if normal_customizer_settings exist, if they exist, display the homepage as we do now, if this doesn't exist display latest news if this is selected.
- [ ] - Create a FrontPage template.

Makes sense ? In the PRO version after we can do the same thing for customizer settings .

**Comment by rodica-andronache** [comment]
Created separated issues for this
