### ISSUE TITLE
Recaptcha not working on mobile devices

### ISSUE THREAD

**Issue by HardeepAsrani** [Codeinwp/zerif-lite#438]
![Image](https://cdn.pbrd.co/images/iYQ0wXWsc.png)

When file upload field is enabled, the reCaptcha isn't working, as seen above. Not sure if we need to fix it with the theme or plugin itself.

**Comment by rodica-andronache** [comment]
I tested with other themes as well, and it seems that it's working with some, but not with all of them, so I think we need to investigate this in the plugin. I'll move the issues there
