### ISSUE TITLE
Remove the contact form options from the theme - back-end part

### ISSUE THREAD

**Issue by rodica-andronache** [Codeinwp/zerif-lite#440]
- Make a fork of the zerif-lite-2 branch and work there
- from customizer.php remove all code for the following controls in the Contact us section: Email address, Button label, Hide recaptcha, Site key and Secret key: http://prntscr.com/cz32ub
- from customizer.js remove all code for zerif_contactus_button_label
- after the contact form is removed, make sure that the contact form is showing when the Pirate Forms is installed
- Note: This issue should be fixed in one individual commit

**Comment by cristian-ungureanu** [comment]
@rodica-andronache I tested with pirate forms and it works fine.
