### ISSUE TITLE
Create Zerif Companion plugin

### ISSUE THREAD

**Issue by rodica-andronache** [Codeinwp/zerif-lite#450]
- Make a fork of the development branch and work there https://github.com/Codeinwp/zerif-companion
- The plugin will be on wp.org, so it needs to follow their rules https://developer.wordpress.org/plugins/wordpress-org/how-your-readme-txt-works/
- In the plugin, we'll register the same widgets as we do in Zerif Lite , so we need to copy all the code for widgets registering from the theme
- It should be something simple, to just copy the code from zerif

Note: This issue should be fixed in one individual commit

**Comment by rodica-andronache** [comment]
https://github.com/Codeinwp/zerif-companion

**Comment by abaicus** [comment]
Here: https://github.com/Codeinwp/themeisle-companion/pull/1/commits/405755b5ea9d8450965a6aabc05d969a7f127a8a
