### ISSUE TITLE
broken widgets our team section

### ISSUE THREAD

**Issue by cristianmenghi** [Codeinwp/zerif-lite#462]
Hi, 
Upgrade from 2.0.0 to 2.0.4 broke section our team, the widgets showed in 4 column in 2.0.0 now show in 1 column, in this section i use the our focus widget.

**Comment by rodica-andronache** [comment]
H @cristianmenghi ,

Thank you for contacting us.Can you please give me your site URL so I can see the issue?

Regards,
Rodica
