### ISSUE TITLE
How to integrate a Twitter feed?

### ISSUE THREAD

**Issue by orschiro** [Codeinwp/zerif-lite#478]
Hi all, 

What's the best way to integrate a Twitter feed into this great theme? :-)

**Comment by rodica-andronache** [comment]
Hi @orschiro ,

Thank you for contacting us! We don't have a specific way for handling Twitter feeds in the theme. You can either use a plugin for this, a widget or insert it directly in a post/page. You can read more about this here for example https://www.elegantthemes.com/blog/tips-tricks/how-to-add-a-twitter-feed-to-your-wordpress-website.

Best regards,
Rodica

**Comment by orschiro** [comment]
Thanks @rodica-andronache!

Right hint in the right direction. :-)

I went for a custom plugin that provides a Twitter hashtag widget. 

The integration into the theme is still a bit rough though...

I will see what I can do to improve it. 

![image](https://cloud.githubusercontent.com/assets/170947/20120498/63303d52-a60d-11e6-8a6d-f446896061b4.png)
