### ISSUE TITLE
Making theme MaxMegaMenu Compatible

### ISSUE THREAD

**Issue by HardeepAsrani** [Codeinwp/zerif-lite#480]
Hi guys,

I see you've added some CSS integration into Zerif Pro (and maybe Lite) for Max Mega Menu - thanks for that!

I was hoping you could make one more edit in style.css:

Find:

```
li.current>a:before {
position: absolute;
margin: auto;
z-index: 1;
content: "";
width: 75%;
height: 2px;
bottom: 0px;
left: 12.5%;
}
```

Replace with:

```
li.menu-item.current>a:before {
position: absolute;
margin: auto;
z-index: 1;
content: "";
width: 75%;
height: 2px;
bottom: 0px;
left: 12.5%;
}
```

This should let the icons in MMM work properly, and shouldn't effect the zerif functionality.

FYI: I have just made a change to MMM which will let the smoothscroll in Zerif work with MMM.

Regards,
Tom

**Comment by rodica-andronache** [comment]
@claudiuvertistudio can you please investigate here and see if he's right, and would not affect the way zerif works?
