### ISSUE TITLE
Prettify About us section Clients area title?

### ISSUE THREAD

**Issue by orschiro** [Codeinwp/zerif-lite#481]
Dear all, 

I am not a designer but maybe someone has an idea how to make the "About us section
Clients area title" a bit more nicely integrated?

Maybe make the title just bigger without the bars to the left and right?

Thank you!

-Robert

![image](https://cloud.githubusercontent.com/assets/170947/20149878/72ccbaaa-a6b3-11e6-9825-267a326b7d70.png)

**Comment by rodica-andronache** [comment]
Hi @orschiro ,

You can add a custom css for that , something like:

`.our-clients .section-footer-title {
    font-size: 25px;
}
.our-clients {
    background: none;
}`

Regards,
Rodica

**Comment by orschiro** [comment]
Dear @rodica-andronache,

This looks much better now.

Thank you very much! :-)

Yours,

Robert

![image](https://cloud.githubusercontent.com/assets/170947/24581970/ed3ea194-1725-11e7-9bd3-0e7e36c6180d.png)
