### ISSUE TITLE
Our Focus widget images not displaying

### ISSUE THREAD

**Issue by deafxlab** [Codeinwp/zerif-lite#484]
I was just prompted to upgrade to Zerif Lite 1.8.5.5. After doing so, images selected in the Zerif - Our focus widgets do not display (see www.deafxlab.com - DEAF X LAB section). Zerif - Team member widgets work fine.

**Comment by rodica-andronache** [comment]
Hi @deafxlab ,

Thank you for contacting us. I checked your site and I couldn't see the issue you mentioned. Is the issue still there? Can you please give me more details?

Thank you,
Rodica

**Comment by deafxlab** [comment]
Hi,

Yes. Still happening. I added a screenshot below. The grey ovals turn red when there’s a mouse-over. Before the update, they displayed the associated image.

Matt

[cid:image001.png@01D24CAB.D3E0A840]

**Comment by rodica-andronache** [comment]
Hi @deafxlab ,

Did this is issue got fixed by clearing the cache too? Please let me know if everything is ok.

Regards,
Rodica

**Comment by deafxlab** [comment]
Yep. Cache clear fixed that too!

Thanks for the follow up. Awesome theme.

Matt

**Comment by rodica-andronache** [comment]
Hi Matt,

Glad to hear that. Thank you very much for the nice words.

Rodica
