### ISSUE TITLE
Logo not displaying correctly

### ISSUE THREAD

**Issue by deafxlab** [Codeinwp/zerif-lite#485]
After upgrading to 1.8.5.5, the Site Identity icon displays too large and continues to appear when a user scrolls down, obscuring content. See www.deafxlab.com.

**Comment by rodica-andronache** [comment]
Hi @deafxlab ,

Again, thank you for contacting us! Is the issue still there? I was not able to see it.

Regards,
Rodica

**Comment by deafxlab** [comment]
Screenshot below. As you can see, the logo (originally smaller) does not remain in the masthead and continues to be on screen as you scroll down – obscuring content.

Thanks,

Matt

[cid:image001.png@01D24CAB.F9FF6A70]

**Comment by rodica-andronache** [comment]
Hi @deafxlab ,

Unfortunately I can't see the screenshot, could you please maybe attach it again using a service like lightshot maybe?
Also, can you please clear your cache? Maybe that's what causing the issues.

Regards,
Rodica

**Comment by deafxlab** [comment]
Clearing the cache worked. Thanks.

**Comment by rodica-andronache** [comment]
Glad to hear that everything is ok :)

Regards,
Rodica
