### ISSUE TITLE
Question : Contact Form 7 Zerif Lite

### ISSUE THREAD

**Issue by loorlab** [Codeinwp/zerif-lite#487]
Hello Friends, we would like to know why they removed the forms of Contact Form 7, we did not realize that the form of the main page stopped working.

Thanks !

**Comment by rodica-andronache** [comment]
Hi @loorlab ,

I'm really sorry for the delay. I'm not sure if you are talking about the contact form that comes with Zerif Lite. If so, yes, we had to remove it to be able to keep the theme in the wordpress.org repository, but that same functionality is kept if you will install the ThemIsle Companion plugin from here https://wordpress.org/plugins/themeisle-companion/. 
Let me know if this is of any help or I if I can do anything else for you.

Regards,
Rodica

**Comment by loorlab** [comment]
@rodica-andronache Oh Thanks for your info.

Contact Form 7 has problems for the current repositories?

Regards !

**Comment by rodica-andronache** [comment]
Hi @loorlab ,

No, we didn't changed anything related to Contact Form 7, so it should work the same.

Regards,
Rodica
