### ISSUE TITLE
Icons of footer

### ISSUE THREAD

**Issue by loorlab** [Codeinwp/zerif-lite#488]
Hi Friends, The usual footer icons are not showing :
![loor 1557 - loor lab - expertos en desarrollo web y wordpress - www_loorlab_com](https://cloud.githubusercontent.com/assets/3799679/20912138/65819e82-bb3b-11e6-91df-1cc38dcc52f9.png)

Thanks !

**Comment by rodica-andronache** [comment]
Hi @loorlab ,

Thank you for contacting us. Can you please give me your site URL so I can see the issue?

Regards,
Rodica

**Comment by loorlab** [comment]
Thanks @rodica-andronache our url http://loorlab.com/ 

Regards, LOOR Lab

**Comment by loorlab** [comment]
Hi @rodica-andronache Any good news? 

Thanks !

**Comment by rodica-andronache** [comment]
Hi @loorlab ,

I'm so sorry for the late answer. Somehow I missed this.
Would you mind installing our dedicated support plugin? It will help us debug the issue more effectively: 
http://bit.ly/themeisle-pirate-parrot
Please see this document on how to install plugins manually if you need help: http://docs.themeisle.com/article/199-how-to-install-wordpress-plugins
After you install the plugin, please go to your WordPress dashboard, then to "Tools" and "ThemeIsle Support Parrot".

Once there, just click on "Call Parrot". The plugin will generate a support token. Please copy-paste it and send it to me here.

Thank you,
Rodica

**Comment by hussain9136** [comment]
Hi @rodica-andronache i am having the exact same problem. I noticed that when i log in to my wordpress account, the icon shows up. But it dosn't show in other devices or when i log out.

**Comment by hussain9136** [comment]
Hi @rodica-andronache, did you resolved the issue? Can you plz help me?

**Comment by rodica-andronache** [comment]
Hi @hussain9136 ,

I'm sorry for the late reply. The fact you are not seeing the footer icons, is because those icons are used as sane defaults. Meaning those are default content (used only for starter content) visible only for logged in users. This is why you are seeing the icons in customizer, but not on the site. 
What you need to do is upload new icons images in customizer, or save on your computer, those used in the theme by default, and after that, upload them in customizer. This way the icons would get saved, and you would see them even if not logged in.

Regards,
Rodica

**Comment by hussain9136** [comment]
rodica-andronache Thank you very much, It works now. Really appreciated.

**Comment by rodica-andronache** [comment]
HI @hussain9136 ,

I'm glad to hear everything is ok now. If I can help you with anything else please let me know.

Regards,
Rodica

P.S. If you are happy with out theme or support you can always leave us a review here https://wordpress.org/support/theme/zerif-lite/reviews/#new-post . It would help us a lot :)

**Comment by nikolaijahn** [comment]
Hi, had the same problem a few seconds ago. Before I realized the problem I was wondering why no data, icons or pictures were in the media library.  Maybe with the next update ?
Anyhow, thank you for the support, love the theme :)
