### ISSUE TITLE
eliminate the need for  page template

### ISSUE THREAD

**Issue by ineagu** [Codeinwp/zerif-lite#501]
@rodica-andronache first thing here, we need to enable the home even using the default page ( like we did for shopisle ), we can do this only for new users ?

**Comment by ineagu** [comment]
this is also a priority.

**Comment by rodica-andronache** [comment]
@abaicus can you please help me test this? it's on my fork here https://github.com/Codeinwp/zerif-lite/pull/533

We need to test for all the cases, with old users ( with the zerif_bigtitle_title_2 option set up for example ), with new users, with or without the option I added in Advanced options to keep the mechanism like normal.
Whit latest posts or static page. With frontpage template.
And we need to make sure the background image works (just for the frontpage and the blog). We need to make sure it's not displaying on internal pages, in none of the cases.
