### ISSUE TITLE
Increase the font size of the title?

### ISSUE THREAD

**Issue by orschiro** [Codeinwp/zerif-lite#508]
Dear all, 

What do you think of increasing the font size of the title?

I think it's very small in comparison to the post headings.

Yours,

Robert

**Example Title:**

![image](https://cloud.githubusercontent.com/assets/170947/23094645/3f2824ca-f5fd-11e6-84ac-c3c74b73dbb7.png)

**Example Heading 2:**

![image](https://cloud.githubusercontent.com/assets/170947/23094647/4719aef6-f5fd-11e6-8d6a-6a4c6ad0eaeb.png)

**Comment by rodica-andronache** [comment]
Hi @orschiro ,

I'm really sorry for the late reply. We are really happy to receive any feedback from our users, and what you suggested it would be a nice change, but unfortunately we can't really make it, considering the number of users we already have.

Regards,
Rodica

**Comment by orschiro** [comment]
Hi @rodica-andronache, 

No problem. I can absolutely understand that you cannot respond to every user request. 

Time for me to tweak it via CSS. :-)
