### ISSUE TITLE
Install themeisle companion notice in customize

### ISSUE THREAD

**Issue by rodica-andronache** [Codeinwp/zerif-lite#509]
on zerif-lite-2 branch
![image uploaded from ios](https://cloud.githubusercontent.com/assets/3266155/23206977/4f2af30e-f8f8-11e6-874a-a149caff9e7d.jpg)

**Comment by ineagu** [comment]
did you have the code to cristi from affluent ?

**Comment by cristian-ungureanu** [comment]
@ineagu , I don't have the code.
