### ISSUE TITLE
After last updae Zerif, the logo is massive !!HELP NEEDED!

### ISSUE THREAD

**Issue by mkokvik** [Codeinwp/zerif-lite#510]
Hi, 
After the last update, the logo for my company is now huge and taking up the entire page. See photo. So I can not have a logo on the page. I have tried to change the logo and the size but this still happens.
![webpage error](https://cloud.githubusercontent.com/assets/25955140/23212021/ab69af62-f8fc-11e6-9ad6-184b7ab1bfbe.jpeg)  

Any help please!!

**Comment by rodica-andronache** [comment]
Hi @mkokvik ,

Thank you for contacting us.
Can you please let me know if you did some CSS changes to the theme? Or if you are not able to select the logo again , and use the option to crop it?

Regards,
Rodica

**Comment by mkokvik** [comment]
we have done some CSS changes but not to the logo part. I can select the logo, but if i crop I will lose the logo as cropping removes 9/10 of the logo. 
Did not have this issue until i updated it today.

**Comment by rodica-andronache** [comment]
Hi,

I that case, can you please open a support ticket here https://themeisle.com/contact/ so I can get more details?
Please mention in the message this issue and that you want it to be assigned to me, so it can be directed to me.

Thank you,
Rodica

**Comment by mkokvik** [comment]
Thank you for your reply. I just installed pirate forms for contact and then i adjusted the contact us fieldd, then i tried to update the logo again. And all of a sudden it works….. i ave been trying for ages to get it to work and suddenly it “magically” sorted itself out… 

thanks for the help anyways.. 

M

**Comment by rodica-andronache** [comment]
Hi,

I am glad to hear everything is ok. Let us know if we can help with anything else.

Regards,
Rodica
