### ISSUE TITLE
Add a big header image on the blog like we have on Llorix

### ISSUE THREAD

**Issue by rodica-andronache** [Codeinwp/zerif-lite#516]
Important: Create a fork of the zerif-lite-2 branch and work there.

- This change we'll be available only for new users. We have a function called zerif_check_if_old_version_of_theme that check if a user is an older one, so you can use that one.

- for the text we'll use THIS THEME SUPPORTS A CUSTOM FRONTPAGE like on llorix

**Comment by ineagu** [comment]
@abaicus I was looking a bit more here on how it looks on w.org and I have some suggestions : 

1. We can make it smaller like : https://www.dropbox.com/s/vj9k4okgtmf486i/Screenshot%202017-03-03%2019.37.00.png?dl=0
2. We can have a line under it, like on llorix
3. We can have a subtitle - https://www.dropbox.com/s/1evpa1jvipgwpc2/Screenshot%202017-03-03%2019.37.31.png?dl=0


I was using some of my mad design skills and I came up with this ( small title + line ), which I think it looks better compared with current solution, thoughts? - https://www.dropbox.com/s/q5gbsigy65u3ad7/Screenshot%202017-03-03%2019.41.15.png?dl=0 ( it may need a setting for a new background image ).

We may experiment more as well.
