### ISSUE TITLE
When ThemeIsle Companion is installed

### ISSUE THREAD

**Issue by rodica-andronache** [Codeinwp/zerif-lite#517]
remove box which allows the deactivation of the plugin from the Customizer

http://prntscr.com/eequvz

**Comment by ineagu** [comment]
+ After the user click install from the customizer for the companion, when he click on activate, do you think is possible to open that in a new page + refresh current page in customizer after 1 sec? the goal would be that the user won't leave his editing experience, same for pirate forms install link

**Comment by ineagu** [comment]
@rodica-andronache currently the user is also redirect to the new page, the idea was that the user wil remain in the customizer.
