### ISSUE TITLE
big title back issue

### ISSUE THREAD

**Issue by ineagu** [Codeinwp/zerif-lite#535]
@rodica-andronache if I go to the big title section and click back, here is what I get : https://www.dropbox.com/s/jcxcge2fn12m162/Screenshot%202017-03-09%2020.19.15.png?dl=0

**Comment by ineagu** [comment]
and I get stucked there

**Comment by ineagu** [comment]
same for the other sections ( safari )

**Comment by rodica-andronache** [comment]
@ineagu i can't replicate this. how did you do it?

**Comment by ineagu** [comment]
Try with wp 4.5 or so, i can look tomorrow at my plugin list as well

**Comment by rodica-andronache** [comment]
yes, it's seem it's not working with wp 4.5
