### ISSUE TITLE
plugins/companion activation

### ISSUE THREAD

**Issue by ineagu** [Codeinwp/zerif-lite#539]
@rodica-andronache I think we can in fact use some custom js api to automatically both install and activate, without redirecting the users to /plugins page, so we would have a button called : "Install & Activate" .

can any of you look into it?

cc @cristian-ungureanu @abaicus

**Comment by rodica-andronache** [comment]
@abaicus can you try to do this also in the About page http://prnt.sc/ewfno6 ?

**Comment by abaicus** [comment]
Sure!

**Comment by rodica-andronache** [comment]
@abaicus for me, in the Useful plugins tab after installing any of the plugins, I see the same Install and activate button http://prntscr.com/f062uh . For you it's working ok?

**Comment by abaicus** [comment]
@rodica-andronache I've checked this with the head checked out @ 408ab048aaed3759faf898e478b909ec6da73efe and it seems that it wasn't working then either.

**Comment by abaicus** [comment]
I don't think this ever worked. I went way back and it seems to be the same. Even though the plugin is installed, the button remains stuck on "Install".

**Comment by ineagu** [comment]
Not a huge deal, customiEr button is more important
