### ISSUE TITLE
Adding a captcha to Contact Form

### ISSUE THREAD

**Issue by HardeepAsrani** [Codeinwp/zerif-lite#54]
A bunch of people are requesting for this feature. It'd be even better if we can have a third-party plugin to use as the contact form.

Same as https://github.com/Codeinwp/zerif-pro/issues/146

**Comment by ineagu** [comment]
@claudiuvertistudio do you think we can find an elegant solution here that will work for both free/pro : https://www.google.com/recaptcha/intro/index.html ( user need to create an account ), it should appear once user start typing the information .
