### ISSUE TITLE
Product page Layout broken with latest Woocommerce update

### ISSUE THREAD

**Issue by poonam9** [Codeinwp/zerif-lite#547]
@rodica-andronache 

After the recent Woocommerce update the product page of Zerif-lite is disturbed a little. Product short description and price field are messing up.

The below code can fix this issue.

```
.woocommerce-product-details__short-description { text-align: left; }
.woocommerce-product-details__short-description ul { margin:0px; }
.woocommerce-page .product .price { float:none; }
.woocommerce-page .woocommerce-product-rating, .woocommerce div.product .woocommerce-product-rating { float: none; }
```

**Comment by cristian-ungureanu** [comment]
@rodica-andronache , I think I'm done here.

**Comment by rodica-andronache** [comment]
@abaicus can you please have a look at Cristi fork here ?  the product page is not full width anymore http://prntscr.com/eupmo0. Also see if there are any other issues
