### ISSUE TITLE
Can't able to show a page as a homepage other than the default frontpage

### ISSUE THREAD

**Issue by poonam279** [Codeinwp/zerif-lite#566]
@rodica-andronache When I try to show a static page as my homepage I can't do this, every time it shows the default frontpage (with all sections)
http://prntscr.com/f34hkg

**Comment by HardeepAsrani** [comment]
@poonam279 You need to navigate to Customizing > Advanced options > General options, and mark "Keep the old static frontpage template?"

**Comment by rodica-andronache** [comment]
@HardeepAsrani someone should also update the zerif lite documentation with all those changes. Would you like to do it? :D
