### ISSUE TITLE
Bug with the frontpage section content

### ISSUE THREAD

**Issue by suyogyashukla** [Codeinwp/zerif-lite#567]
If we leave the content of the front page sections to the one which comes by default in the demo, it doesn't appear when you log out of the site. For example, if you leave the ribbon section button's content to "Get in touch" which is what comes with the theme by default, it won't show on the site once you log out. It also happens if you leave the "left content" of the about us section to the one which comes by default. I tried to reproduce this at my end and succeeded. 

HelpScout thread: https://secure.helpscout.net/conversation/356132106/131609/?folderId=212390

cc @rodica-andronache @cristian-ungureanu

**Comment by rodica-andronache** [comment]
@suyogyashukla the way it works is this. That content is a sane default, which means it only appears by default for logged in users. To make it visible when no logged in, you just need to save that option, even like add a white space at the end, and then remove, to have the text exactly the same as the default one. 
I also tested it, for the ribbon section, you just need to change the button link and button label as I mentioned before, with a small change, and then you can have it the same (for example Get in touch ) and it's working. So it's not an issue, he can still have Get in touch there, just make sure both the button link and button label are saved in the database
