### ISSUE TITLE
Our focus section widget not working

### ISSUE THREAD

**Issue by suyogyashukla** [Codeinwp/zerif-lite#578]
You can't edit the content. It shows this: https://prnt.sc/f8l94f

HS:- https://secure.helpscout.net/conversation/365519652/133338/?folderId=212390

I saw 3-4 more helpscout threads but couldn't find them rn. Will add more as I see them :)

https://wordpress.org/support/topic/in-our-focus-section-cant-add-own-required-content-and-image/

https://secure.helpscout.net/conversation/365897530/133396/?folderId=212385

**Comment by suyogyashukla** [comment]
More of these coming in: https://secure.helpscout.net/conversation/365913738/133402/?folderId=212385

This needs to be taken care of urgently. @rodica-andronache @cristian-ungureanu @abaicus

**Comment by UVLabs** [comment]
+1

**Comment by vandrenskl** [comment]
any status update?

**Comment by rodica-andronache** [comment]
Hi @vandrenskl ,

We are really sorry for this. We detected the issue here and we'll release an update in the next hour. Thank you for your patience.

Regards,
Rodica

**Comment by vandrenskl** [comment]
@rodica-andronache  great, had fix the bugs, appreciate and thank you so much
