### ISSUE TITLE
child themes in About Zerif Lite 

### ISSUE THREAD

**Issue by dascalescuro** [Codeinwp/zerif-lite#581]
The Child Theme showcase in the WP Dashboard, we are linking to some broken pages

https://wp-themes.com/zblackbeard/
https://wp-themes.com/onepirate/
https://wp-themes.com/zerius/
https://wp-themes.com/zifer-child/

The only one that is kinda working is https://wp-themes.com/responsiveboat/

Why aren't we sending to our own demo page?

**Comment by dascalescuro** [comment]
@rodica-andronache I saw that we are trying to convert users from child themes to Zerif, but we still have this tab in the dashboard: http://prntscr.com/g5wird

+ the broken demos :)

Should we remove it?

**Comment by rodica-andronache** [comment]
I think we can remove them.

**Comment by ineagu** [comment]
yep, we can remove that tab for now, later on we can show multiple demos in that form maybe
