### ISSUE TITLE
Default demo data is not showing after installing the theme

### ISSUE THREAD

**Issue by poonam279** [Codeinwp/zerif-lite#585]
@rodica-andronache When we install the theme and setup a static page as homepage then the default demo data (like heading, subheading,  content, features, buttons) of all sections don't show on the front if we are not login to the WordPress dashboard. See screenshots: http://prntscr.com/fbwmhx http://prntscr.com/fbx3hy

**Comment by rodica-andronache** [comment]
@poonam279 yes, that's how it's supposed to work. they're sane defaults, meaning some default values that appear only for the logged in users, and have an informative sense, like saying how a specific text can be changed. It was one of the requirements to have Zerif Lite back on wordpress.org repository :)
