### ISSUE TITLE
Missing translation strings in wpml-config.xmp

### ISSUE THREAD

**Issue by HardeepAsrani** [Codeinwp/zerif-lite#587]
I found a bug in zerif lite that leads to missing strings in the translation menu. The missing strings are:

```
zerif_bigtitle_title_2
zerif_bigtitle_redbutton_label_2
zerif_ourfocus_title_2
```

@rodica-andronache

**Comment by rodica-andronache** [comment]
@HardeepAsrani thanks :D for such minor issues you can always just fix it directly, if you want :D
