### ISSUE TITLE
Compatibility with Nivo slider - shows a background image at bottom

### ISSUE THREAD

**Issue by poonam279** [Codeinwp/zerif-lite#589]
@rodica-andronache when we replace the big title section with Nivo Slider shortcode it shows the background image at the bottom. See screenshot: http://prntscr.com/ffempt
Same with the Onepirate theme.

**Comment by Vishakha-Patel** [comment]
@rodica-andronache 
I see the same problem in Pro theme too. https://secure.helpscout.net/conversation/506495415/152411?folderId=212385
