### ISSUE TITLE
import/export lite->pro

### ISSUE THREAD

**Issue by ineagu** [Codeinwp/zerif-lite#59]
@rodica-andronache inafara de chestia cu postMessage, mai este foarte important sa gasim o solutie pentru a face export/import din lite in PRO, ideal ar fi o chestie in customizer prin care userul exporta un json ceva cu setari pe care le poate apoi copia in PRO .

Daca ma gandesc mai bine, nu se poate pur si simplu uita tema pro la instalare dupa setarile de la lite ? nu are acces ?

@selu91 tu ai vreo idee ?

**Comment by selu91** [comment]
Da, știu ca mi-ai mai zis de asta și găsisem ca se poate sa vezi dacă a
avut lite înainte și sa ii imporți setările.
