### ISSUE TITLE
Conflict with Elementor Pro (page builder)

### ISSUE THREAD

**Issue by mileamadalin** [Codeinwp/zerif-lite#591]
@rodica-andronache 

BUG - the Elementor 'text size' editor appears to be buggy - does not change the text size when using Elementor Pro

Could you please fix this item.

Elementor have had a look at the back end of www.storeit4less.co.nz..
All of the plugins were turned off and the Zerif theme changed to a default theme.

Outcome:
The below message was received this morning from Gabriel at Elementor.

Message from Elementor:
Gabriel replied
Hi Tim,
Thank you for sending that.
The problem is with your theme Zerif lite.

Send to the developers of your theme the following error messages and let us know if they could sort it out. Tell them that we use the Tinymce text editor:

TypeError: Cannot set property 'onload' of null
at https://www.storeit4less.co.nz/wp-includes/js/tinymce/tinymce.min.js?ver=4603-20170530 - 11:19927
2017-06-12 13:18 +00:00
x 2 times

TypeError: Cannot read property 'html' of undefined
at https://www.storeit4less.co.nz/wp-content/plugins/elementor/assets/js/editor.min.js?ver=1.4.6 - 6:11089
2017-05-11 07:28 +00:00

TypeError: Cannot set property 'onload' of null
at https://www.storeit4less.co.nz/wp-includes/js/tinymce/tinymce.min.js?ver=4506-20170408 - 10:25592
2017-05-04 01:19 +00:00

TypeError: Cannot read property 'html' of undefined
at https://www.storeit4less.co.nz/wp-content/plugins/elementor/assets/js/editor.min.js?ver=1.4.5 - 6:11089
2017-05-03 03:57 +00:00
x 2 times

TypeError: Cannot read property 'html' of undefined
at http://www.storeit4less.co.nz/wp-content/plugins/elementor/assets/js/editor.min.js?ver=1.4.4 - 6:10816
2017-04-27 03:47 +00:00

TypeError: Cannot read property 'trim' of undefined
at http://www.storeit4less.co.nz/wp-content/plugins/elementor/assets/js/editor.min.js?ver=1.4.2 - 4:31571
2017-04-13 02:44 +00:00

SecurityError: Blocked a frame with origin "http://www.storeit4less.co.nz" from accessing a cross-origin frame.
at http://www.storeit4less.co.nz/wp-includes/js/tinymce/tinymce.min.js?ver=4403-20160901 - 2:13752
2017-04-02 01:15 +00:00

**Comment by rodica-andronache** [comment]
@abaicus apparently just removing that, is causing other issues as seen here http://wraith.themeisle.com/wraith/codeinwp/zerif-lite/development/gallery.html Can you please help me on this? :D
