### ISSUE TITLE
SOLVED: Conflict with Anpress 4 comments

### ISSUE THREAD

**Issue by breescorner** [Codeinwp/zerif-lite#592]
Hi, I've been referred by Anspress re: comments not loading. They state, "theme is loading all contents using ajax. Hence most of JS fails to execute which relays on document ready state. You should contact you theme author for fixing this issue (please see https://anspress.io/questions/question/comments-dont-display-on-anpress-4/ ).

Any suggestion on how I can fix this?

**Comment by rodica-andronache** [comment]
Hi @breescorner ,

We are not very familiar with the Anspress plugin, so we would need a little bit more details to investigate this, and see if there is something we can do. Can you please give me your site URL so we can see the issue? Also, where exactly are the comments that are not loading?

Thank you,
Rodica

**Comment by breescorner** [comment]
Thank-you for your reply, Rodica. The site is www.ogles.org. Here is a [screenshot](https://drive.google.com/file/d/0BzTs4gnwfR8KYk9NcVpJS3REem8/view?usp=sharing) of what Anspress looks like with Zerif (gorgeous btw!)...  Notice that the test thread has 1 comment, but when I click the comment button it will not show the comment. That's the only bug... I am still able to write and submit a comment, but nobody can see it except admin from inside the dashboard.
