### ISSUE TITLE
Testimonial Section - How to change Background color 

### ISSUE THREAD

**Issue by vandrenskl** [Codeinwp/zerif-lite#593]
Hi,

i need help, i try to use the testimonial section to put my video and it success but meanwhile, the background color had change. how to change it? please advice.

thank you
![image4](https://user-images.githubusercontent.com/28749131/27283619-c1df3816-5527-11e7-81a0-76a7fdb5dc16.png)

**Comment by rodica-andronache** [comment]
Hi,

Unfortunately, changing the colors is available just in the pro version https://docs.themeisle.com/article/65-zerif-lite-versus-zerif-pro
