### ISSUE TITLE
zerif Our Focus Section not working on other pages using SiteOrigin Page Builder

### ISSUE THREAD

**Issue by hussain9136** [Codeinwp/zerif-lite#598]
Hi, I am using SiteOrigin Page Builder for my page and i am trying to use Zerif-Our Focus widget, but the upload image button seems not working. Same when i am using Zerif-Our Team widget. It's working fine on the front page but causing issue when trying on SiteOrigin Page only. Thanks

@rodica-andronache

**Comment by rodica-andronache** [comment]
Hi @hussain9136 ,

It seems there was a problem in the Themeisle Companion plugin causing this. Can you please update the plugin to the latest version and let me know if after that, everything is ok?

Thank you,
Rodica

**Comment by hussain9136** [comment]
Hi @rodica-andronache ,
I updated the plugin, and i did resolve the core issue. Now i can upload the image but the Text below and the social icons are aligned left, and not in the center like one on the front page. How do i make them center aligned?
Thanks.

**Comment by hussain9136** [comment]
Finally i resolved it. The CSS code given in the instruction was not working for me (Idk why). So i played with the codes and changed it from 
`.siteorigin-panels .zerif_team .col-lg-3 { width: 100% !important; text-align: center; }`
to
`.siteorigin-panels .team-box { width: 100% !important; text-align: center; }
`
And it worked perfectly. :)

Thanks @rodica-andronache for your help.
