### ISSUE TITLE
SOLVED: Carousel stuck (wont scroll on home page)

### ISSUE THREAD

**Issue by breescorner** [Codeinwp/zerif-lite#601]
I have a problem with the home page carousel on the home page. It won't scroll left or right. Please advise. Site is [here](https://www.ogles.org). PS: I just solved another problem with comments not showing in Anspress, and a woomerce bug (linked products) ... and then this happened. I deactivated all plugins then turned them on one-by-one initially .. so this was unexpected.

**Comment by rodica-andronache** [comment]
Hi @breescorner ,

I can't reach your site http://prntscr.com/fx20v0.

Rodica

**Comment by breescorner** [comment]
Sorry @rodica-andronache ... I think it's the firewall:( But I figured it out. It's a conflict between the carousel, custom post type (snowball) and the way categories are shown on the home page carousel. I fixed it by excluding those custom post types from the home page. They never show to begin with and I have no idea why they're suddenly acting up.
