### ISSUE TITLE
Not able to change the order of sections in frontpage

### ISSUE THREAD

**Issue by thandie777** [Codeinwp/zerif-lite#602]
Hi, I'm having trouble changing moving up a ribbon section.  I just want to change the order of some sections, so I thought I would just need to change the template-frontpage.php file. I moved that on the child theme and proceeded to rearrange the order in there moving up the get_template_part related to the ribbon..
Nothing happens! Any one knows how to do that?

**Comment by rodica-andronache** [comment]
Hi thandie777,

Reordering frontpage sections is a pro feature. If you want, you can check out http://themeisle.com/themes/zerif-pro.

Regards,
Rodica
