### ISSUE TITLE
Buttons missing in header and footer

### ISSUE THREAD

**Issue by purplecodes** [Codeinwp/zerif-lite#616]
@rodica-andronache 

The header and footer buttons are not appearing. 
https://prnt.sc/h3668l
Tried to install the theme from scratch on my local host and setup a footer, I got the same issue.

**Comment by bacoetrom** [comment]
Did you solve the problem?

**Comment by rodica-andronache** [comment]
Hi @bacoetrom,

Those images are sane defaults, meaning that they appear only for logged in users, as a usage example. To be sure you're images display, you can either upload different images, or save on your computer the default images or the images from our demo https://demo.themeisle.com/zerif-lite/ and upload them again in the customizer.

Regards,
Rodica
