### ISSUE TITLE
In the preview our team doesn't show right

### ISSUE THREAD

**Issue by ineagu** [Codeinwp/zerif-lite#62]
@rodica-andronache if you look here : https://wordpress.org/themes/zerif-lite at the preview, our team doesn't looks right, can you fix it tomorrow ?

**Comment by rodica-andronache** [comment]
@ineagu ca sa apara la preview trebuie sa modific tema pe wp.org, nu? si nu o sa dureze ceva pana aproba?

**Comment by ineagu** [comment]
pai tu modifici pe github, si eu pun pe wp.org, cand aproba aproba, poate dura o zi sau 5. :dart:
