### ISSUE TITLE
Menu not responsive in iPad

### ISSUE THREAD

**Issue by stefan-cotitosu** [Codeinwp/zerif-lite#623]
The menu is not centered under the logo on iPad, it takes more than one row and it stays on the right side.

http://prntscr.com/hcvg2g

**Comment by stefan-cotitosu** [comment]
+1

**Comment by rodica-andronache** [comment]
@stefan-cotitosu did you see this problem on any user? or on your local site? Because I can't seem to be able to replicate this. 
I only see it on the demo for now, and I want to make sure it's only there or not 👍

**Comment by stefan-cotitosu** [comment]
@rodica-andronache  

Yes, it is on a user site. Try it on the iPad, not only in the browser.

URL: http://surreysellers.com/
Ticket: https://secure.helpscout.net/conversation/454114403/146087?folderId=212385
