### ISSUE TITLE
Customizing client widget doesn't work

### ISSUE THREAD

**Issue by erinknight242** [Codeinwp/zerif-lite#625]
When I try to change the widget image and link from the default for the frontpage client widget, I get   this "An error has occurred" message every time, and it doesn't save my changes. This isn't a problem with my internet connection, since I'm able to post here. Everything else in the wordpress editor is working, just not the client widgets.

<img width="296" alt="client-error" src="https://user-images.githubusercontent.com/3969554/33154049-434202f0-cfab-11e7-82b2-c4f1c93981d8.png">

**Comment by rodica-andronache** [comment]
Hi @erinknight242 ,

Could you please give more details? Which version of the theme are you using? Are you using a child theme? Are you using Orbit Fox Companion plugin? Which version? 
Did you installed your theme using FTP or using the WordPress Dashboard?
Are there any notices in the Dashboard area?

Regards,
Rodica

**Comment by erinknight242** [comment]
I am using a child theme, and I'm seeing the issue on both version 1.8.5.30 and 1.8.5.32. I am using the Orbit Fox Companion on both, version 2.1.0. I just updated it to 2.2.0 and it looks like that fixed the issue, thanks.
