### ISSUE TITLE
Compatibility with Pirate Forms

### ISSUE THREAD

**Issue by rodica-andronache** [Codeinwp/zerif-lite#626]
@bogdanpopa90 could you please check the compatibility here https://prnt.sc/hkrfrl with all 3 options for spam trap?

+ plus on internal pages
+ plus the attachment field

**Comment by mileamadalin** [comment]
@rodica-andronache 

+ 1 

Customer image

<img width="1156" alt="screen-shot-2017-12-26-at-1 55 57-pm" src="https://user-images.githubusercontent.com/6906834/34387534-06e9779e-eb2f-11e7-8fb7-fd8dfa815f10.png">
