### ISSUE TITLE
Home page hangs in Edge and sometimes Explorer browsers

### ISSUE THREAD

**Issue by breescorner** [Codeinwp/zerif-lite#628]
Hello, I've been getting bug reports from users saying that the home page is hanging. Apparently the spinner just keeps spinning. Any advice on how to troubleshoot this?

**Comment by rodica-andronache** [comment]
Hi @breescorner,

Could you please give me your site URL so I can see the issue?

Thanks,
Rodica

**Comment by breescorner** [comment]
@rodica-andronache www.ogles.org. PS, I think it may be due to a conflict with another plugin and it might be fixed. But please see if you agree.

**Comment by rodica-andronache** [comment]
@breescorner if you found out it's a conflict with a plugin, let me know what plugin is, and in which cases it makes the page to hang. From what I've tested, I couldn't see this happening

**Comment by breescorner** [comment]
It's Holler Box. I had to deactivate it because I had way too many bug reports.

BTW.. I'm running a family membership site on PMPRO, who is promoting the plugin to its users. 

https://it.wordpress.org/plugins/holler-box/

**Comment by rodica-andronache** [comment]
Hi @breescorner ,

Ok, thanks for letting me know. Unfortunately, at this moment, there isn't something we can do with the theme to make it compatible with the plugin.

Regards

**Comment by breescorner** [comment]
@rodica-andronache It's fine. Thank-you for helping me again:)
