### ISSUE TITLE
Latest News Issue in iPad

### ISSUE THREAD

**Issue by HardeepAsrani** [Codeinwp/zerif-lite#63]
In the landscape mode, only one Latest News item is appearing. It's working perfectly on laptop with Responsive Design View.

![iPad](http://s11.postimg.org/omb2qxi0j/IMG_0198.png)

**Comment by ineagu** [comment]
did he tried to click on the left arrow ? maybe the slider just auto-scrolled ..

**Comment by HardeepAsrani** [comment]
This shot is from my device & it tried all the slides.
