### ISSUE TITLE
Links not working on mobile

### ISSUE THREAD

**Issue by erinknight242** [Codeinwp/zerif-lite#631]
Links work fine on desktop, but at mobile size, there is a div that covers up the screen and blocks the text so links aren't clickable.

If I put `display: none` on this block, the links work again. My content is in the main article block, not the sidebar.

Screenshot, showing the offending block:
<img width="323" alt="sidebar-wrap" src="https://user-images.githubusercontent.com/3969554/34137330-fcca4438-e42f-11e7-8d81-7ab1384b6e42.png">

**Comment by rodica-andronache** [comment]
Hi @erinknight242,

Could you please point me to your site URL so I can actually see the content?

Regards,
Rodica

**Comment by erinknight242** [comment]
http://www.lonestarcurlingclub.org/?page_id=2 was the page in the screen shot above. I added z-index to the sidebar-wrap and the main content-left-wrap to work around the issue.

**Comment by rodica-andronache** [comment]
Hi @erinknight242,

The problem is related to this Member portal link from the sidebar https://prnt.sc/hxkf6a . I'm not sure how you added it there but it seems to go outside the sidebar wrap which is causing these problems on mobile.

Regards,
Rodica
