### ISSUE TITLE
Investigate possible fatal error when using a child theme

### ISSUE THREAD

**Issue by rodica-andronache** [Codeinwp/zerif-lite#638]
https://wordpress.org/support/topic/fatal-error-upon-updating-to-the-most-recent-version-of-the-theme/

**Comment by vandrenskl** [comment]
Hi,
  
 Thanks for your e-mail and for your info, currently I'm at oversea with limited email and phone access started on 10 March 2018 until 13 March 2018.
  
 For any issues, please contact Ms. Mai: mai@v-clouds.net
  
 Thank you and regards,
KL Sit
Co-Founder & Director
