### ISSUE TITLE
Zerif Lite Elementor Template

### ISSUE THREAD

**Issue by radu-themeisle** [Codeinwp/zerif-lite#651]
Make an Elementor Template that recreates the demo page:
https://demo.themeisle.com/zerif-lite/

**Comment by radu-themeisle** [comment]
- FEATURES: Created the parallax image, and then made 1000x1000 px images for the 4 features so that they integrated in the block. I didn't try to recreate the exact number of rows of text using padding because when the user will change the text it might not look ok, instead I adjusted the gap between the features. Transformed border and image radius from px to percentage to make sure it's rounded properly on any device. Adjusted colored divider width.
- About: counters need an additional plugin so we either keep the icons or at most use the progress bars (I'd go with the icons): http://prntscr.com/j6069l
- Footer:
1. I tried using Icon box for the first 3 columns but the spacing of the elements cannot be fully controlled (see the middle column, the one with the envelope), the other 2 (address and phone) are made using 2 segments, an icon and text, which you can set spacing as needed (even with negative values)
2. In order to make the 4th column be black from top to bottom I had to set the top & bottom padding of the other 3 columns to 100px
3. Hovering the social icons colors them like on the demo, but the Themeisle link gets the color from the customizer settings.

**Comment by ineagu** [comment]
for about we can keep some icons. you can attach the export here when is ready

**Comment by radu-themeisle** [comment]
- Blog / Latest News: section is made using Post Type Grid, was able only to style the Typography
- Footer: decided with @rodica-andronache to got with separate icon and text editor blocks to have the section look as close as possible to the demo
- Contact: form is called using shortcode so I only styled the Typography

The template is done, but the images will not import with the template. I researched why and found a discussion on Git that they only import if the template was exported from a live site so that Elementor can retrieve the images from there when you import the template. Instead, it will display a placeholder image.

I can setup a live link as I worked on Local.

[Zerif Lite Elementor Template.zip](https://github.com/Codeinwp/zerif-lite/files/1919964/Zerif.Lite.Elementor.Template.zip)

**Comment by ineagu** [comment]
cool, @abaicus would take it from here at some point :)

**Comment by rodica-andronache** [comment]
@radu-themeisle did Andrei add this in OBFX? :D I'm asking because if not, we should somehow don't forget about this

**Comment by radu-themeisle** [comment]
In theory this will be launched with the Content Importer, so for now we should just not forget about it, or maybe add a task  with the template to the Content Importer thread.

**Comment by rodica-andronache** [comment]
yes, you can add a task so we don't forget about it, please :)

**Comment by ineagu** [comment]
I think we can launch it before as well, we’ll have the import when is ready and well try to migrate zerif users

**Comment by radu-themeisle** [comment]
I've added the template in Sizzify Pro (via https://github.com/Codeinwp/elementor-premium-templates/issues/2)
