### ISSUE TITLE
Change Elementor notice from 5 days to 30 days

### ISSUE THREAD

**Issue by rodica-andronache** [Codeinwp/zerif-lite#653]
https://github.com/Codeinwp/hestia-pro/issues/1452

**Comment by cristian-ungureanu** [comment]
@rodica-andronache in zerif lite we only recommend beaver builder. Do you want me to add elementor too? Or to increase beaver's time?

**Comment by rodica-andronache** [comment]
@cristian-ungureanu isn't this for elementor https://github.com/Codeinwp/zerif-lite/blob/30476bf6b466cc4898a6fe24ec3e5f27d1001a23/functions.php#L429 ?

**Comment by cristian-ungureanu** [comment]
I'm closing this issue because Elementor was removed from lite https://github.com/Codeinwp/zerif-lite/pull/652/commits/74816d339f35c67573d8267be3e9c3bf654366cd
