### ISSUE TITLE
Smooth scroll on mobile for frontpage sections

### ISSUE THREAD

**Issue by rodica-andronache** [Codeinwp/zerif-lite#656]
@cosmin-serbanescu after the latest changes it seems that there is a problem on mobile when scrolling from the navigation menu to the front page sections. It scrolls to that section, but it passes it a little bit. I tested with the default menu and indeed it's happening.
https://wordpress.org/support/topic/section-links-not-scrolling-to-the-right-place-on-mobile-after-update/

Please have a look on this, with both the default menu and mega menu.

**Comment by cosmin-serbanescu** [comment]
@rodica-andronache , it was due to the fact that after clicking on a section link the responsive menu closes and that modifies the calculated offset used by scrolling. Took the chance and closed also the menu generated by max mega menu.

**Comment by rodica-andronache** [comment]
@cosmin-serbanescu gg 👍
