### ISSUE TITLE
How do I resize Google maps on the Zerif Theme

### ISSUE THREAD

**Issue by reubenleon** [Codeinwp/zerif-lite#660]

**Comment by rodica-andronache** [comment]
Hi @reubenleon! What exactly do you mean by resizing the map section? What do you want to obtain?

P.S. If you are using our premium products you can contact us here also http://themeisle.com/contact

**Comment by reubenleon** [comment]
It won't go full size across the whole screen


________________________________

**Comment by rodica-andronache** [comment]
Hi @reubenleon,

Can you share your site URL? And on which device do you have this problem?

Regards,
Rodica

**Comment by reubenleon** [comment]
Www.triplevengineering.co.uk<http://Www.triplevengineering.co.uk>

And it's on all devices

Sent from my iPhone

On 16 May 2018, at 13:43, Rodica-Elena Andronache <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi @reubenleon<https://github.com/reubenleon>,

Can you share your site URL? And on which device do you have this problem?

Regards,
Rodica

**Comment by rodica-andronache** [comment]
Hi @reubenleon ,

I see your site is in maintenance mode so I can't really see the problem. I think it would be best to contact us here http://themeisle.com/contact so we can get more details.

Regards,
Rodica
