### ISSUE TITLE
Add notice for Hestia

### ISSUE THREAD

**Issue by rodica-andronache** [Codeinwp/zerif-lite#679]
instead of Fagri https://github.com/Codeinwp/zerif-lite/issues/678.
The notice should be active **only until November 1st**, when it's going to be replaced by the notice for the new theme

For the actual text @sab2ina can help 👍

**Comment by sab2ina** [comment]
We're adding 2 scheduled notices:

1. Notice for **Hestia** - visible until Nov 1st:

Check out our **best free theme in 2018**, fully compatible with your current Zerif Lite theme.
We guarantee a smooth transition to this new theme, without any options being lost.

- **best free theme in 2018** the link opens Hestia in the WP dashboard like we did for Fagri

2. Notice for **Neve** - after Nov 1st, remove the above and replace it with:

This theme is no longer maintained. Instead, we’ve just launched **our newest theme**, it's free and it's superb. We guarantee a smooth transition to this new theme, without any options being lost.

Read more about the renaming and **our next plans** for Zerif.

- _**our newest theme**_ will have a redirect link for Neve on TI, @selul can help here
- _**our next plans**_ links to the article on the TI blog - I will get back with the URL for this

@rodica-andronache @cristian-ungureanu let me know if it looks good to you

**Comment by cristian-ungureanu** [comment]
The function will look like kinda like this https://github.com/Codeinwp/hestia-pro/blob/c14e1c3f6b1dea7520a9db6bb3c29ba90328ded4/functions.php#L170 but instead of comparing with the date when the theme was activated, we'll compare with a fixed date.
