### ISSUE TITLE
Social icons error

### ISSUE THREAD

**Issue by jesa29** [Codeinwp/zerif-lite#680]
Description:
Social icons don't work, if there's no Facebook link

I've tried to add Instagram link, but nothing happens and there's no icon. I don't have any other social links. When I add something to Facebook link - appears both Facebook and Instagram  icons with links

**Comment by rodica-andronache** [comment]
Hi @jesa29,

Indeed there is a problem with the social icons, but it seems that's only happening in customizer, and not on the actual site. So, until that's fixed, you can try and see if, on the actual site, everything is ok, and you can only add the Instagram link.

**Comment by jesa29** [comment]
Sure, I've tried to look not through customizer - because of known issue with other icons in footer - and it was the same result

**Comment by rodica-andronache** [comment]
which version of the theme are you using?

**Comment by jesa29** [comment]
1.8.5.43

**Comment by rodica-andronache** [comment]
Try to update to the latest version 1.8.5.44 👍

**Comment by jesa29** [comment]
Ok, thnx
