### ISSUE TITLE
Investigate transfer from lite to pro using child themes

### ISSUE THREAD

**Issue by rodica-andronache** [Codeinwp/zerif-lite#694]
Here I think we need to find out if he's using a child theme or not. If so, maybe the problem is that he would need to use something like this https://docs.themeisle.com/article/769-how-to-upgrade-from-hestia-to-hestia-pro-when-using-child-themes to transfer the content from lite to pro.
https://secure.helpscout.net/conversation/689066253/171772/

From what I've read, the notices may be caused by is_child_theme()
https://github.com/presscustomizr/hueman-addons/issues/46

**Comment by cristian-ungureanu** [comment]
This was fixed in pro version. The part with notices I couldn't replicate.

**Comment by rodica-andronache** [comment]
I couldn't replicate the notices either for now
