### ISSUE TITLE
Fallback for lower php versions

### ISSUE THREAD

**Issue by rodica-andronache** [Codeinwp/zerif-lite#702]
we got this "Reasons for reporting this theme, in depth explanation.: My site is breaking all over the place after the host initiated a PHP upgrade, https://www.buscadorwine.com: Parse error: syntax error, unexpected T_PAAMAYIM_NEKUDOTAYIM in /home2/buscador/public_html/wp-content/themes/zerif-lite/functions.php on line 520"
From what I've seen, this is happening for lower than 5.3 php versions, that we don't support. We should test this and add the fallback we have in neve and hestia https://github.com/Codeinwp/neve/blob/0255a9ed3f66425b201d92228a8d68128f1c5868/functions.php#L51

**Comment by stefan-cotitosu** [comment]
@rodica-andronache I can't manage to fix this.

I've tested with PHP 5.2.17. I am able to replicate the issue, but the code suggested is not working.
I tried this code.
```
/**
 * Adds notice for PHP < 5.3.29 hosts.
 */
function zerif_php_support() {
	$theme_name = wp_get_theme()->Name;
	$message = sprintf(
	/* translators: 1 - message to upgrade PHP to the latest version, 2 - theme name */
		__( 'Hey, we\'ve noticed that you\'re running an outdated version of PHP which is no longer supported. Make sure your site is fast and secure, by %1$s. %2$s\'s minimal requirement is PHP 5.4.0.', 'zerif-lite' ),
		sprintf(
		/* translators: %s message to upgrade PHP to the latest version */
			'<a href="https://wordpress.org/support/upgrade-php/">%s</a>',
			__( 'upgrading PHP to the latest version', 'zerif-lite' ),
			$theme_name
		)
	);

	printf( '<div class="error"><p>%1$s</p></div>', wp_kses_post( $message ) );
}

if ( version_compare( PHP_VERSION, '5.3.29' ) < 0 ) {
	/**
	 * Add notice for PHP upgrade.
	 */
	add_filter( 'template_include', '__return_null', 99 );
	switch_theme( WP_DEFAULT_THEME );
	unset( $_GET['activated'] );
	add_action( 'admin_notices', 'zerif_php_support' );
	return;
}
```

Also, Neve is failing too on PHP 5.2.17. Theme version 1.0.28 from wordpress.org
![neve-fail-on-php5 2](https://user-images.githubusercontent.com/26867648/51245401-3499f200-1990-11e9-8496-1175a9401a22.png)

From what I understand, that code should change the current theme with the WordPress default theme and display a notice. The code seems to be executed too late, so a fatal error is happening before it.

**Comment by rodica-andronache** [comment]
@stefan-cotitosu this should happen when you try to **activate** the theme. And instead of activating Neve/Zerif you would stay with the default theme, and get a message in the dashboard. Have you tried this?

**Comment by stefan-cotitosu** [comment]
Not yet, I thought that it would happen when the theme is already activate. 

Makes more sense like you said. I will try. Thanks 👍
