### ISSUE TITLE
new screenshot

### ISSUE THREAD

**Issue by ineagu** [Codeinwp/zerif-lite#81]
@rodica-andronache @DragosBubu the wporg team is still discussing the newest screenshot standards ( since the old one isn't looking so good on the site) I think it will be : 1200x900, so at some point once the decision is final we should update all the lite themes to reflect that .

For now we can try to update zerif lite screenshot to 1200x900, please compress the image as good as possible.

**Comment by ineagu** [comment]
@DragosBubu 

alte mici comentarii : 

- am putea lumina poza de background putin mai mult, mai spre https://wordpress.org/themes/make dar nu asa mult
- am putea mari zona de our focus mai aproape de ce era initial si sa mai 'taiem' putin din zona de sus ?
- cat de complex ar fi sa facem niste iconite custom gpl ca aici : http://demo.themeisle.com/zerif-pro/ ?

Per total cel mai important lucru este ca in view-ul asta : http://awesomescreenshot.com/0694n7wv30 screenshotul sa atraga cel mai bun si lumea sa dea click si banuies ca niste culori putin mai vii ar ajuta la asta :D

**Comment by ineagu** [comment]
@DragosBubu inca nu e suficient de luminata imaginea comparativ cu restul.

De asemenea se pare ca pe laptop in wp-admin imaginea e fortata la : 349x262 si asta de ex se vede urat, te mai poti juca cu ea sa vezi exact cum apare in wp-admin la add new thmes si cum sa atraga atentia ?

**Comment by ineagu** [comment]
@DragosBubu cei de la colorway care sunt pe locul 1, au incercat un screenshot si mai mic ( 600x450 ) care totusi nu se vede rau si au pus un mic background gri : https://i0.wp.com/themes.svn.wordpress.org/colorway/3.3.0/screenshot.png?w=1142&strip=all, iar la dimensiunea mica din wp-admin nu se strica.

**Comment by DragosBubu** [comment]
@ineagu Ok, am inteles.
Pot sa incerc niste iconite GPL

**Comment by ineagu** [comment]
nu stiu daca problema sunt iconitele, poate dimensiunea noua e prea mare si se vede f aiurea la resize,

**Comment by DragosBubu** [comment]
Nu cred ca sunt o problema, dar putem sa incercam ceva al nostru, oamenii o sa aprecieze atentia la detalii.
Da, de acord, o sa incerc o dimensiune mai mica pt screenshot

**Comment by ineagu** [comment]
da, dar asta e pe planul 2, as vrea intai sa gasim o dimensiune si un model
ok care sa se vada bine mic

2015-03-25 12:07 GMT+01:00 Dragos BUBU <notifications@github.com>:

**Comment by rodica-andronache** [comment]
@ineagu aici mai facem ceva?
