### ISSUE TITLE
About Us rating circles

### ISSUE THREAD

**Issue by mariusghitulescu** [Codeinwp/zerif-lite#86]
If Contact Us section is disabled, the rating circles in About Us section no longer work properly.

Instead of rating circles, some text boxes appear instead.

Demo here: https://themeisle.com/forums/topic/icons-problem-about-us-section/#post-310689

**Comment by rodica-andronache** [comment]
Am facut eu un alt issue cu problema asta deja :D asa ca-l inchid pe asta

**Comment by mariusghitulescu** [comment]
ok
