### ISSUE TITLE
Upload Images does not work 

### ISSUE THREAD

**Issue by mileamadalin** [Codeinwp/zerif-lite#89]
@rodica-andronache 
Looks like we have some problems with the buttons. The message from the client:

I want to upload images in Sections ( team, focus, testimonials, clients )

> > but it does not work. Hitting the Upload Images has no effect.
> > Nothing happens at all.
> > I even tried to drag and drop an image onto the field. What happens is: the path on my computer towards that pic is written. But again - when hitting the upload button - there´s no effect.
> > At the moment I can not add any picture - nor by uploading or by taking from the WP-mediathek.
> > The only image that has worked so far is the background picture.

**Comment by ineagu** [comment]
@mileamadalin before creating an issue can you also investigate it ? here I feel that is more or less an isolated problem in this case we should have all details like plugins/browser etc.

For you works?

**Comment by ineagu** [comment]
@rodica-andronache sa imi zici cand vrei sa punem pe wp.org aici.

**Comment by rodica-andronache** [comment]
@mileamadalin merge uploadul , daca poti, raspunde clientului, sa apese pe butonul de Apply, dupa ce uploadeaza poza, ca sa mearg
